### PR TITLE
driver: get access list for balance calculation

### LINKED ISSUE #3252: bug: driver does not use access lists when simulating pre-hooks while computing balances
### Problem
This [order](https://explorer.cow.fi/gc/orders/0x9955075846884c8a992b5d61bdb8cc11b4049fe23ebda2420d7f8e0599364ecf5a945741f5c367410678e1513b939f7adafbacf067917f5d?tab=overview) was filled sub-optimally in 2 partial fills.
It contains a pre-hook that claims rewards to provide the full sell token balance to the owner. The driver already computes the available balances for an order based on the outcome of the pre-hooks (if there are any). But in this case the balance simulation didn't show that the owner would get all the necessary sell tokens from the hook so it reported the available balance to be whatever the owner currently has without the hook.
A solver picked up this order and executed it. In the actual settlement the hook got executed and unlocked the remaining sell tokens which led to another partial fill that then fulfilled the order completely.

When simulating the hook on its own it exceeds its gas limit and therefor reverts. This explains why no balance change happens in the simulation. However, in the actual settlement the balance change happened.
When comparing the [hook simulation](https://dashboard.tenderly.co/cow-protocol/solver-slippage/simulator/460b7ac7-6935-4800-9034-80cae63d5490) with the onchain settlement [simulation](https://www.tdly.co/tx/100/0xadf0c46fee5d5e728eb8959bb411b92ff36e44b6eb150ec911ddee9dd95ef538) it became apparent that executing the hook as part of the actual settlement was a lot cheaper.

The reason seems to be that the storage loads are a lot cheaper in the real settlement. That is likely caused by the fact that we use access lists for the real solution but not during the balance simulation.

### Impact
The driver fails to compute an order's accurate available balance when hooks unlocking sell tokens set a tight gas limit.

### Expected behaviour
The simulation for computing the available balance should be as close to the real settlement as possible to avoid these differences.
The easy fix is to just use access lists for during the balance simulation, too.

### PR DESCRIPTION
**Pull request by m-lord-renkse**
# Description
From the task:
This [order](https://explorer.cow.fi/gc/orders/0x9955075846884c8a992b5d61bdb8cc11b4049fe23ebda2420d7f8e0599364ecf5a945741f5c367410678e1513b939f7adafbacf067917f5d?tab=overview) was filled sub-optimally in 2 partial fills.
It contains a pre-hook that claims rewards to provide the full sell token balance to the owner. The driver already computes the available balances for an order based on the outcome of the pre-hooks (if there are any). But in this case the balance simulation didn't show that the owner would get all the necessary sell tokens from the hook so it reported the available balance to be whatever the owner currently has without the hook.
A solver picked up this order and executed it. In the actual settlement the hook got executed and unlocked the remaining sell tokens which led to another partial fill that then fulfilled the order completely.

When simulating the hook on its own it exceeds its gas limit and therefor reverts. This explains why no balance change happens in the simulation. However, in the actual settlement the balance change happened.
When comparing the [hook simulation](https://dashboard.tenderly.co/cow-protocol/solver-slippage/simulator/460b7ac7-6935-4800-9034-80cae63d5490) with the onchain settlement [simulation](https://www.tdly.co/tx/100/0xadf0c46fee5d5e728eb8959bb411b92ff36e44b6eb150ec911ddee9dd95ef538) it became apparent that executing the hook as part of the actual settlement was a lot cheaper.

The reason seems to be that the storage loads are a lot cheaper in the real settlement. That is likely caused by the fact that we use access lists for the real solution but not during the balance simulation.

# Changes
- Get the access list before simulating the balance

## How to test
1. Regression tests

## Related Issues
Fixes #3252

### CODE REVIEW

File: crates/driver/src/infra/blockchain/token.rs [hunk 1]
```diff
@@ -111,29 +116,42 @@ impl Erc20 {
...
+        // Create the access list for the balance simulation
+        if let Some(from) = &method.tx.from {
+            let access_list_tx = Tx {
+                from: from.address(),
+                to: method.tx.to,
+                value: method.tx.value,
+                data: method.tx.data.clone(),
+                access_list: method.tx.access_list,
+            };
+            let access_list = self.ethereum.create_access_list(access_list_tx).await.ok();
```
Comment (MartinquaXD) [inline crates/driver/src/infra/blockchain/token.rs:149]: The `Balances` contract is not actually deployed so this `create_access_list` call would do nothing useful. Instead you'd have to compute the access list for the call that `contracts::storage_accessible::simulate()` executes under the hood.

File: crates/driver/src/infra/blockchain/mod.rs [hunk 2]
```diff
@@ -70,6 +74,26 @@ struct Inner {
     current_block: CurrentBlockWatcher,
 }
 
+pub struct Tx {
```
Comment (mstrug) [inline crates/driver/src/infra/blockchain/mod.rs:77]: I'm not convinced we need this intermediary type.

**Review by mstrug — COMMENTED** [review]
Is it possible to run simulation with access lists in Tenderly to compare the gas usage?

File: crates/driver/src/infra/blockchain/mod.rs (hunk 2 above)
Comment (m-lord-renkse) [reply crates/driver/src/infra/blockchain/mod.rs:77]: If we don't have this type, then from the tx builder we would need to unwrap before calling the function just so in the function it is done `a: Some(a)`. I am open to suggestions!

**Comment by squadgazzz** [comment]
If this is still WIP, please convert it to draft.

**Comment by m-lord-renkse** [comment]
> If this is still WIP, please convert it to draft.

technically it is not WIP, I received comments which need to be reworked 🤔 but the more eyes and reviews I get the better.

**Review by squadgazzz — APPROVED** [review]
LGTM, assuming there is a plan for ensuring the change works properly.

File: crates/driver/src/infra/blockchain/token.rs [hunk 3]
```diff
@@ -111,29 +116,47 @@ impl Erc20 {
...
+                })
+                .collect(),
+        );
+        let access_list_call = contracts::storage_accessible::call(
+            method.tx.to.unwrap(),
+            contracts::bytecode!(contracts::support::Balances),
+            method.tx.data.clone().unwrap(),
+        );
+        // Create the access list for the balance simulation
+        if let Some(from) = &access_list_call.from {
```
Comment (MartinquaXD) [inline crates/driver/src/infra/blockchain/token.rs:146]: Unless I'm missing something this is not necessary. Either from is not set at all or it's using the zero address. Either case could be used to simplify this code.

File: crates/driver/src/infra/blockchain/mod.rs (hunk 2 above)
Comment (MartinquaXD) [reply crates/driver/src/infra/blockchain/mod.rs:77]: Seems like unwrapping would be the better choice than introducing more identically named types.

File: crates/driver/src/infra/blockchain/token.rs [hunk 4]
```diff
@@ -143,17 +143,15 @@ impl Erc20 {
...
-                data: access_list_call.data.clone(),
-                access_list: access_list_call.access_list,
-            };
-            let access_list = self.ethereum.create_access_list(access_list_tx).await.ok();
-            method.tx.access_list = access_list.map(Into::into);
-        }
+        let access_list_tx = Tx {
+            from: access_list_call.from.unwrap_or_default(),
+            to: access_list_call.to,
+            value: Some(0.into()),
```
Comment (m-lord-renkse) [inline crates/driver/src/infra/blockchain/token.rs:149]: This being `None` (which seems to be always `None`) or `0` does not affect the result.

**Review by mstrug — APPROVED** [review]

File: crates/driver/src/infra/blockchain/mod.rs (hunk 2 above)
Comment (MartinquaXD) [reply crates/driver/src/infra/blockchain/mod.rs:78]: The introduction of this new type is still not sitting right with me.
I played a bit around with the code and I believe what you can do is to adjust `create_access_list()` to use this signature `    pub async fn create_access_list<T>(&self, tx: T)  -> Result<eth::AccessList, Error>  where web3::types::CallRequest: From<T> {
` and follow the compiler errors from there.
That way this function can take any type that can be converted to a `CallRequest`. Then you could implement `From<eth::Tx> for web3::types::CallRequest` to make the existing code pass and the `CallRequest` returned from `contracts::storage_accessible::call` could be passed in directly.

**Review by MartinquaXD — COMMENTED** [review]
FYI I researched a bit why we need to set `to` to `None`. If `to == None` the node interprets the calldata as a SC constructor call instead of a function call. The storage accessible simulation magic works by creating a new contract and in the contractor call the function we actually care about it.

File: crates/driver/src/infra/blockchain/mod.rs (hunk 2 above)
Comment (m-lord-renkse) [reply crates/driver/src/infra/blockchain/mod.rs:78]: Good proposal, I like it! 👌

Comment (m-lord-renkse) [reply crates/driver/src/infra/blockchain/mod.rs]: nice, it works well, re-tested it! thanks for the comment, really nice one!

**Review by squadgazzz — APPROVED** [review]
LGTM

**Review by MartinquaXD — APPROVED** [review]
