### PR TITLE
Use unscaled user fees for executed amounts

### LINKED ISSUE #2150: bug: Wrong executed amounts in competition data
### Problem
It seems that the data on the buy and sell amounts of orders added in #1975 is not accurate.
This is only implemented on staging if I understand correctly.

For example, the transaction with hash `0x2548006a1bf02717d4e0a20bd6f0db7e8762d146161135f2d22f857eb726740d` gives executed amounts
image
but the sell amount on etherscan
image
and our order book endpoint
image
are different.

### Impact
Having the correct data in the competition endpoint is required for EBBO tests.

### Expected behaviour
I expect that the "sellAmount" and "buyAmount" in the competition endpoint to be the amounts send and received by a user in that settlement.

### PR DESCRIPTION
**Pull request by fleupold**
# Description
Market orders currently return incorrect executed amounts (cf. #2150) because we report the fee amount solvers are supposed to use for scoring (which add the 0.002 ETH gas subsidy we currently apply on user orders to compensate the gas overhead in the settlement contract). 
However, this fee amount is only used for scoring (to avoid solutions getting rejected because of negative scores) and is not what the user actually pays.

# Changes

- [ ] Rename current "solver_fee()" method on `Trade` to `scoring_fee()` as it captures more accurately what this specific value should be used for (I started renaming all occurrences of solver_fee which imply this semantic, but this diff is becoming huge.
- [ ] Introduce a new `fee` method which returns the fee from the user perspective (namely the subsidised fee in the case of market orders)
- [ ] Use 👆 when computing executed fee amount
- [ ] Added integration tests for the fee amount behavior

## How to test
Newly added tests

## Related Issues

Fixes #2150

### CODE REVIEW

File: crates/driver/src/tests/setup/mod.rs [hunk 1]
```diff
@@ -767,6 +772,10 @@ impl<'a> Solve<'a> {
             blockchain: self.blockchain,
         }
     }
+
+    pub fn not_ok(self, code: hyper::StatusCode) {
+        assert_eq!(self.status, code);
+    }
```
Comment (MartinquaXD) [inline crates/driver/src/tests/setup/mod.rs:778]: The name `not_ok` is weird since you could also pass `200` as the expected `code`, no?
Maybe just `status()` instead?

**Review by MartinquaXD — APPROVED** [review]
