### PR TITLE
Don't return error if 0x API cannot respond to quote

### LINKED ISSUE #1003: 0x Solver not finding solution because of insufficient liquidity treated as error
When the 0x single order solver cannot respond to a quote request because there is not enough liquidity, this gets treated as an error and causes alerts:

```
DEBUG auction{id=4931095 run=467}: shared::zeroex_api: Querying 0x API: https://gated.api.0x.org/swap/v1/quote?sellToken=0x6b175474e89094c44da98b954eedeac495271d0f&buyToken=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&enableSlippageProtection=false&sellAmount=1998739482660737315328&slippagePercentage=0.003&affiliateAddress=0x9008D19f58AAbD9eD0D60971565AA8510560ab41&skipValidation=true&intentOnFilling=false
DEBUG auction{id=4931095 run=467}: shared::zeroex_api: Response from 0x API: {"code":100,"reason":"Validation Failed","validationErrors":[{"field":"sellAmount","code":1004,"reason":"INSUFFICIENT_ASSET_LIQUIDITY","description":"We are not able to fulfill an order for this token pair at the requested amount due to a lack of liquidity"}]}
WARN auction{id=4931095 run=467}: solver::solver::single_order_solver: Solver 0x error: 0x Response Error UnknownZeroExError("Validation Failed")
```

This is expected behaviour, shouldn't be counted as an error and not cause an alert.

### PR DESCRIPTION
**Pull request by fleupold**
Fixes #1003.

It is possible that for some tokens the 0x API cannot find a route and therefore responds with a validation error (of subtype insufficient liquidity). This is currently treated as an unknown 0x error and contributes to the failure count, which we alert on.

However, not being able to trade a token because of insufficient liquidity is not really something we should alert on. This PR changes the get_quote function signature and turns validation errors in a `Ok(None)` result. Alternatively we could introduce a special error type (e.g. Benign) that doesn’t end up getting treated as a regular error. However, I felt that given our extensive use of `?` when handling the swap response, we might miss some call-site that should treat benign errors slightly differently

### Test Plan

Unit tests

### CODE REVIEW

**Review by vkgnosis — APPROVED** [review]

**Review by nlordell — APPROVED** [review]
Looks good.

One thing I am not a fan of is that both [1Inch](https://github.com/cowprotocol/services/blob/d014f9b2aefab99306a9c57a7463347fc938b154/crates/shared/src/oneinch_api.rs#L362-L364) and [ParaSwap](https://github.com/cowprotocol/services/blob/d014f9b2aefab99306a9c57a7463347fc938b154/crates/shared/src/paraswap_api.rs#L92-L93) use `Error`s to indicate insufficient liquidity, and I would slightly prefer that here for consistency (And conceptually, insufficient liquidity is a kind of pricing error that we want to handle differently when solving).

**Comment by fleupold** [comment]
Re-requesting review since the approach is now very different (and therefore the PR need to be re-evaluated)

File: crates/shared/src/trade_finding/zeroex.rs [hunk 1]
```diff
@@ -94,7 +94,14 @@ impl TradeFinding for ZeroExTradeFinder {
...
 impl From<ZeroExResponseError> for TradeError {
     fn from(err: ZeroExResponseError) -> Self {
-        TradeError::Other(err.into())
+        match err {
+            ZeroExResponseError::ServerError(_) => TradeError::Other(err.into()),
+            ZeroExResponseError::UnknownZeroExError(_) => TradeError::Other(err.into()),
+            ZeroExResponseError::InsufficientLiquidity => TradeError::NoLiquidity,
+            ZeroExResponseError::DeserializeError(_, _) => TradeError::Other(err.into()),
+            ZeroExResponseError::TextFetch(_) => TradeError::Other(err.into()),
+            ZeroExResponseError::Send(_) => TradeError::Other(err.into()),
```
Comment (nlordell) [inline crates/shared/src/trade_finding/zeroex.rs:103]: Ubernit: You should be able to make this more succinct without needing `_`:
```
            ZeroExResponseError::InsufficientLiquidity => TradeError::NoLiquidity,
            err @ ZeroExResponseError::ServerError(_)
                | ZeroExResponseError::UnknownZeroExError(_)
                | ZeroExResponseError::DeserializeError(_, _)
                | ZeroExResponseError::TextFetch(_)
                | ZeroExResponseError::Send(_) => TradeError::Other(err.into()),
                => TradeError::Other(err.into()),
```

**Review by nlordell — APPROVED** [review]
