### PR TITLE
[EASY] Fix `solver_competition_v2::load_by_tx_hash` SQL query

### LINKED ISSUE #3481: bug: Fix `solver_competition_v2::load_by_tx_hash` SQL query
### Problem
The following error was noticed in the logs:
```
2025-07-11T11:38:02.553Z ERROR request{id="881fab40fb9666ccd88bc5e7abb8ef06"}: orderbook::api::get_solver_competition_v2: load solver competition err=solver_competition::load_by_tx_hash

Caused by:
    0: error occurred while decoding column 0: unexpected null; try decoding as an `Option`
    1: unexpected null; try decoding as an `Option`
```
The SQL query needs to be fixed to avoid that.

### Impact
Failing requests instead of returning clear Not Found responses.

### To reproduce
Easy to reproduce in tests. In real world scenario, it might be more complicated, which requires a settlement without the observations table populated.

### Expected behaviour
None should be returned instead of Error.

### PR DESCRIPTION
**Pull request by squadgazzz**
# Description
Fixes an SQL issue mentioned in #3481:

> The following error was noticed in the logs:
> ```
> 2025-07-11T11:38:02.553Z ERROR request{id="881fab40fb9666ccd88bc5e7abb8ef06"}: orderbook::api::get_solver_competition_v2: load solver competition err=solver_competition::load_by_tx_hash
> 
> Caused by:
>     0: error occurred while decoding column 0: unexpected null; try decoding as an `Option`
>     1: unexpected null; try decoding as an `Option`
> ```

# Changes
This change ensures that `load_by_tx_hash` handles cases where `settlements.auction_id` is NULL.

- Uses Option<i64> in the SQLx query to avoid runtime decoding errors when the column is null.
- Applies `.flatten()` to handle the Option<Option<_>> from fetch_optional. An alternative solution is to declare a wrapper struct, which contains an optional single value, but flattening is concise enough.
- Prevents panics when the `settlement_observations` row is missing or when `auction_id` is not yet set.

## How to test
Added a new test. It is quite involved to add a positive case scenario, where all the corresponding tables are also filled out, so I kept things simple for now. Will test it in staging first.

## Related Issues

Fixes #3481
Requires #3482 to fix the issue completely

### CODE REVIEW

**Review by fafk — APPROVED** [review]

File: crates/database/src/solver_competition_v2.rs [hunk 1]
```diff
@@ -71,17 +71,18 @@ pub async fn load_by_tx_hash(
     tx_hash: TransactionHash,
 ) -> Result<Option<SolverCompetition>, sqlx::Error> {
     const FETCH_AUCTION_ID: &str = r#"
-        SELECT auction_id
+        SELECT s.auction_id
         FROM settlements s
         LEFT OUTER JOIN settlement_observations so ON
```
Comment (MartinquaXD) [inline crates/database/src/solver_competition_v2.rs]: The same can be achieved with a regular `JOIN`, right? I copied that part over from the old endpoint without much scrutiny.
```suggestion
        JOIN settlement_observations so ON
```

Comment (MartinquaXD) [reply crates/database/src/solver_competition_v2.rs]: Isn't the `AND s.auction_id IS NOT NULL` already handled by using a regular `JOIN`? If a row does not have the `auction_id` there will be nothing that can be joined on top of it.

Comment (squadgazzz) [reply crates/database/src/solver_competition_v2.rs]: The initial settlements row gets inserted without the `auction_id` field: https://github.com/cowprotocol/services/blob/97ddf0c55b1ab7a41bd026ed5bfe7a95fd86f9ed/crates/database/src/events.rs#L128-L145
Since we are joining on other fields, the `auction_id` can be NULL.
