### PR TITLE
Store auction with liquidity

### LINKED ISSUE #2633: feat: Store auction instances including liquidity
### Problem
Since switching solvers to the new auction format, auction instances from the driver (including liquidity) are not stored anymore. Since those instances have been used for EBBO testing, some EBBO checks are currently not working.

Since we want to move forward with formalizing EBBO, having auctions instances is required to get a better overview of the magnitude of EBBO violations.

### Suggested solution
Store auction instances from one of the solvers which receives liquidity, similarly to how it was done for the legacy format. Auction instances from the autopilot are not enought since they do not contain liquidity.

### PR DESCRIPTION
**Pull request by Mateo-mro**
# Description
Store auction instances from one of the solvers which receives liquidity, similarly to how it was done for the legacy format. Auction instances from the autopilot are not enough since they do not contain liquidity.

## How to test
1. Regression tests
2. It can be tested in staging by configuring quasidomo and checking the S3 bucket

Fixes #2633

### CODE REVIEW

File: crates/driver/src/infra/persistence/dto.rs [hunk 1]
```diff
@@ -0,0 +1,398 @@
+use {
```
Comment (Mateo-mro) [inline crates/driver/src/infra/persistence/dto.rs:1]: We had two options here:
- create the dto for storing this information in the S3
- using the already existing `Auction` and `Liquidity` structs and derive everything needed for serialization, etc

I decided to do the first option mostly for better data control and encapsulation. But I am open to changes, of course.

File: crates/autopilot/src/infra/persistence/dto/order.rs [hunk 2]
```diff
@@ -258,7 +258,6 @@ impl From<boundary::EcdsaSignature> for domain::auction::order::EcdsaSignature {
     }
 }
 
-#[serde_as]
```
Comment (Mateo-mro) [inline crates/autopilot/src/infra/persistence/dto/order.rs:261]: It doesn't look like this is needed.

File: crates/driver/src/infra/persistence/dto.rs (hunk 1 above)
Comment (fleupold) [reply crates/driver/src/infra/persistence/dto.rs:1]: I think given that @fhenneke's goal is to use this file and replay it against an existing solver implementation (Quasimodo) using the exact same representation as what we send to solvers would make sense. In fact, an alternative implementation approach would be to simply write another solver engine that doesn't compute anything but simply updates the received instance file and returns an empty solution.

File: crates/driver/src/infra/persistence/mod.rs [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+pub struct S3 {
+    /// The s3_instance_upload_* arguments configure how auction instances
+    /// should be uploaded to AWS S3.
+    /// They must either all be set or all not set.
+    pub s3_instance_upload_bucket: String,
+
+    /// Prepended to the auction id to form the final instance filename on S3.
+    /// Something like "staging/mainnet/"
+    pub s3_instance_upload_filename_prefix: String,
+}
```
Comment (fleupold) [inline crates/driver/src/infra/persistence/mod.rs:27]: nit: How will this look like in the config? Maybe we can make it a subtype with shorter name a la:
```toml
[s3]
bucket = "..."
prefix = "..."
```

File: crates/driver/src/infra/persistence/mod.rs [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+        if let Some(s3) = &config.s3 {
+            Self {
+                s3: Some(Arc::new(s3::Uploader::new(s3.clone().into()).await)),
+            }
+        } else {
+            Self { s3: None }
+        }
+    }
+
+    /// Saves the given auction with liquidity
```
Comment (fleupold) [inline crates/driver/src/infra/persistence/mod.rs:54]: nanonit: document fire and forget mentality (so the caller doesn't think this may be blocking an upload of a large file

File: crates/driver/src/infra/solver/mod.rs [hunk 5]
```diff
@@ -108,10 +113,12 @@ pub struct Config {
     /// TODO: Remove once all solvers are moved to use limit orders for quoting
     pub quote_using_limit_orders: bool,
     pub merge_solutions: SolutionMerging,
+    /// S3 path for storing the auctions with liquidity
```
Comment (fleupold) [inline crates/driver/src/infra/solver/mod.rs:116]:
```suggestion
    /// S3 configuration for storing the auction in the form they are sent to the solver engine
```

**Review by fleupold — COMMENTED** [review]
Looks pretty good to me. I would consider serialising the solver-dto object instead of creating a new one (as I believe this is what will be the main use case of this feature)

**Review by fleupold — CHANGES_REQUESTED** [review]
Domain objects are supposed to be pure logic structs and should not implement serialisation to be passed around (that's for infra dto representations of those objects)

File: crates/driver/src/util/bytes.rs [hunk 6]
```diff
@@ -2,6 +2,24 @@
...
+    }
+}
+
+impl AsRef<[u8]> for Bytes<[u8; 56]> {
+    fn as_ref(&self) -> &[u8] {
+        &self.0
+    }
+}
+
+impl AsRef<[u8]> for Bytes<[u8; 32]> {
```
Comment (MartinquaXD) [inline crates/driver/src/util/bytes.rs:17]: These can probably be turned into one implementation using const generics.

**Review by MartinquaXD — COMMENTED** [review]
I agree that we should not (de)serialize domain structs and instead should store the stringified dto structs.

File: crates/driver/src/infra/persistence/mod.rs [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+#[serde(rename_all = "camelCase")]
+struct AuctionWithLiquidity {
+    auction: Auction,
+    liquidity: Vec<Liquidity>,
+}
+
+#[serde_as]
+#[derive(Serialize)]
+#[serde(rename_all = "camelCase")]
+struct Liquidity {
```
[the remark this answers is not in the document]
Comment (MartinquaXD) [reply crates/driver/src/infra/persistence/mod.rs:25]: There is no need to add any new DTOs or serialize implementations. IIUC you could simply upload the file [here](https://github.com/cowprotocol/services/blob/main/crates/driver/src/infra/solver/mod.rs#L189) without having to worry about any serialization because the request body was already serialized. And since you have access to the `solver` there you should be able to call the respective upload function from there.

[the remark this answers is not in the document]
Comment (Mateo-mro) [reply crates/driver/src/infra/persistence/mod.rs]: @MartinquaXD I understand, thanks for pointing it out. I changed it so now the body is updated to the S3, which contains the desired auction + liquidity + some small extra configuration which may be nice to have.

File: crates/driver/src/infra/persistence/mod.rs [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+
+    /// Saves the given auction with liquidity with fire and forget mentality
+    /// (non-blocking operation)
+    pub fn archive_auction(&self, auction_id: Option<Id>, body: &str) {
+        let Some(uploader) = self.s3.clone() else {
+            return;
+        };
+        let Some(id) = auction_id else {
+            return;
+        };
```
Comment (MartinquaXD) [inline crates/driver/src/infra/persistence/mod.rs:54]: Deciding that auctions without ids (i.e. quote requests) should not be uploaded seems like a domain decision to me. If `archive_auction` were to take a non-optional `Id` this would naturally be enforced by the type system in the domain logic.

Also there should be a comment somewhere explaining why we only store auctions which have an id.

File: crates/driver/src/infra/config/file/mod.rs [hunk 9]
```diff
@@ -225,6 +225,11 @@ struct SolverConfig {
     /// auction together.
     #[serde(default)]
     merge_solutions: bool,
+
+    /// S3 configuration for storing the auction in the form they are sent to
```
Comment (MartinquaXD) [inline crates/driver/src/infra/config/file/mod.rs:229]:
```suggestion
    /// S3 configuration for storing the auctions in the form they are sent to
```

File: crates/driver/src/infra/persistence/mod.rs [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+    std::sync::Arc,
+    tracing::Instrument,
+};
+
+#[derive(Clone, Debug, Default, Deserialize)]
+#[serde(rename_all = "kebab-case", deny_unknown_fields)]
+pub struct S3 {
+    /// The s3_instance_upload_* arguments configure how auction instances
+    /// should be uploaded to AWS S3.
+    /// They must either all be set or all not set.
```
Comment (MartinquaXD) [inline crates/driver/src/infra/persistence/mod.rs:13]: `s3_instance_upload_*` is no longer a thing.
> They must either all be set or all not set.

Since we now use a config file instead of env variables this is finally enforced by the deserialization logic so we don't have to mention it anymore.

And finally this comment doesn't really explain what a bucket is.

File: crates/driver/src/infra/config/file/mod.rs [hunk 11]
```diff
@@ -1,6 +1,6 @@
 pub use load::load;
 use {
-    crate::{domain::eth, util::serialize},
+    crate::{domain::eth, infra::persistence::S3, util::serialize},
```
Comment (MartinquaXD) [inline crates/driver/src/infra/config/file/mod.rs:3]: Although it often seems like unnecessary boiler plate there should be a separate struct that defines the config format which get used to initialize the s3 struct.
That's the reason why the new config struct is the only thing that gets imported here. All the other config formats have been defined inside this file and therefore didn't need to be imported.
This separation between `config representation` <-> `struct used in the core logic` <-> `dto` allows us to very freely modify each component without propagating this change down the whole chain. Because we didn't do that diligently in the old code modifying anything of the `Order` in the `api` is extremely annoying.

File: crates/driver/src/infra/persistence/mod.rs [hunk 12]
```diff
@@ -0,0 +1,70 @@
+use {
+    crate::{domain::competition::auction::Id, infra::solver::Config},
+    serde::Deserialize,
+    std::sync::Arc,
+    tracing::Instrument,
+};
+
+#[derive(Clone, Debug, Default, Deserialize)]
+#[serde(rename_all = "kebab-case", deny_unknown_fields)]
```
Comment (MartinquaXD) [inline crates/driver/src/infra/persistence/mod.rs:9]: A good rule of thumb is probably that nothing should ever have to be (de)serialized outside of config loading and request sending. That way the separation between domain and everything else becomes very clear. Maybe we can even have a clippy lint for that to really enforce the DDD style separation of concerns regarding this. 🤔

**Review by MartinquaXD — COMMENTED** [review]
Almost there. Mostly nits and comments regarding DDD.

File: crates/driver/src/infra/persistence/mod.rs (hunk 12 above)
Comment (Mateo-mro) [reply crates/driver/src/infra/persistence/mod.rs:9]: @MartinquaXD I see your point. In the end it is a matter of architectural decision, There are also advantages of doing it how I did it: each module is standalone and controls all the data (config, dto and domain), and the config module would be just an aggregator of configs. As it is in the code, everything is in the module (dto and domain) but not the config. Each way has its cons/pros.

I personally like it more when each module has full control, but if all the modules are gathered like that it makes no sense for me to break that consistency. I would create chaos :ok_hand:

File: crates/driver/src/infra/persistence/mod.rs (hunk 8 above)
Comment (Mateo-mro) [reply crates/driver/src/infra/persistence/mod.rs:54]: Sure! I'll move it to the domain logic. 
I believe (I may be wrong) that auctions without id are only the ones generated by `fake_auction` function :thinking:

File: crates/driver/src/infra/persistence/mod.rs (hunk 12 above)
Comment (Mateo-mro) [reply crates/driver/src/infra/persistence/mod.rs:9]: I think having a clippy is a good idea, but sine there is (de)serialization also in all the `dto` modules within the domain logic, I am not so sure `clippy` can be customized so fine to detect and skip all of those :thinking:

File: crates/driver/src/infra/persistence/mod.rs (hunk 8 above)
Comment (MartinquaXD) [reply crates/driver/src/infra/persistence/mod.rs]: > I believe (I may be wrong) that auctions without id are only the ones generated by fake_auction function

Yes, that's right. Those are the quote requests which don't really make sense to store.

File: crates/driver/src/infra/persistence/mod.rs [hunk 13]
```diff
@@ -0,0 +1,75 @@
...
+    pub fn archive_auction(&self, auction_id: Id, body: &str) {
+        let Some(uploader) = self.s3.clone() else {
+            return;
+        };
+        let body = body.to_string();
+        tokio::spawn(
+            async move {
+                match uploader.upload(auction_id.to_string(), body).await {
+                    Ok(key) => {
+                        tracing::info!(?key, "uploaded auction to s3");
```
Comment (squadgazzz) [inline crates/driver/src/infra/persistence/mod.rs:65]: Do we really need this log at the INFO level?

**Review by squadgazzz — APPROVED** [review]
LGTM

File: crates/driver/src/infra/persistence/mod.rs (hunk 13 above)
Comment (Mateo-mro) [reply crates/driver/src/infra/persistence/mod.rs:65]: It was `info` for autopilot, but maybe it is better to change it to debug no to spam too much :ok_hand:

**Review by fleupold — APPROVED** [review]
LGTM
