### PR TITLE
Make tx gas limit configurable in driver

### LINKED ISSUE #3777: Transaction encoding is incompatible with Fusaka hardfork
### Problem
The fusaka hardfork introduces a protocol level cap on the gas limit of individual transactions (2^24). Currently our access list creation configures tx gas limits equal to the block gas limit.

### Impact
Solution encoding in the reference driver fails on Sepolia (and soon all other chains enabling Fusaka).

### To reproduce
Do a trade on sepolia

If it's simply enough to make this gas limit configurable we should probably do that - otherwise we should just hardcode the limit of 2^24 - 1. See [here](https://github.com/cowprotocol/services/blob/main/crates/driver/src/infra/blockchain/mod.rs#L196-L218).

### PR DESCRIPTION
**Pull request by m-sz**
Required to fix Sepolia after fusaka hard fork.

# Description
Sepolia got broken because the fusaka hard fork introduced a protocol level cap on tx gas limit which currently is being set to the block gas limit (which is too high).

# Changes
Make tx gas limit configurable in the driver, preserving the old behaviour (of taking block gas limit) if it is not specified.
- [ ] Add tx_gas_limit command line argument (env: TX_GAS_LIMIT)

## How to test
1. Configure limit to 2^24 - 1 and test if transactions can be made on Sepolia
2. 
## Related Issues

Fixes #3777

### CODE REVIEW

File: crates/driver/src/infra/cli.rs [hunk 1]
```diff
@@ -46,4 +47,9 @@ pub struct Args {
     /// https://github.com/cowprotocol/services/blob/main/crates/driver/example.toml.
     #[clap(long, env)]
     pub config: PathBuf,
+
+    /// Transaction gas limit
+    /// If not specified, uses current block's gas limit
```
Comment (jmg-duarte) [inline crates/driver/src/infra/cli.rs]:
```suggestion
    /// Transaction gas limit.
    /// If not specified, it uses current block's gas limit.
```

**Review by jmg-duarte — APPROVED** [review]
nit, but it's g2g due to the urgency IMO

File: crates/driver/src/infra/cli.rs [hunk 2]
```diff
@@ -46,4 +47,9 @@ pub struct Args {
...
+    #[clap(long, env)]
+    pub tx_gas_limit: Option<U256>,
```
Comment (squadgazzz) [inline crates/driver/src/infra/cli.rs]: Maybe we should be a bit more specific with the naming, since it is used only for the creation of access lists. Are there any other places where we set the gas limit in this crate and should we also switch to the same config param?

Comment (m-sz) [reply crates/driver/src/infra/cli.rs]: I have checked the driver's source code and found no other instances where we specify the tx gas limit. It is only related to the creation of access lists.

**Review by squadgazzz — DISMISSED** [review]
LGTM. Shouldn't be merged until an infra PR is ready.

**Review by squadgazzz — APPROVED** [review]
