### PR TITLE
Solver participation guard

### LINKED ISSUE #3221: feat: Kick out solver from competition if not settling
### Problem
When a solver repeatedly wins consecutive auctions but fails to settle its solutions on-chain, it can lead to system downtime. To prevent this, the autopilot must have the capability to temporarily exclude such solvers from participating in competitions. This ensures no single solver can disrupt the system's operations.

### Suggested solution
Introduce a new `domain::competition` component to control whether a `/solve` request should be sent to a solver. This component would handle two responsibilities:

#### Solver Authorization
Utilize the existing logic `eth.contracts().authenticator().is_solver()` to verify if a solver is whitelisted.

#### Settlement Performance Tracking
Implement statistics-based logic to identify solvers that have won the last X auctions but failed to deliver settlements on-chain. This logic would also encompass other criteria for evaluating a solver’s reliability based on settlement success.

All required data is already accessible via the database. For example, given the auction X, we can fetch data from the previous N auctions, including full competition details. Additionally, the `settlement::Observer` populates a relationship between settlements and auctions. This allows us to confirm whether a settlement exists for a specific auction before its deadline.

### PR DESCRIPTION
**Pull request by squadgazzz**
# Description
From the original issue:
> When a solver repeatedly wins consecutive auctions but fails to settle its solutions on-chain, it can lead to system downtime. To prevent this, the autopilot must have the capability to temporarily exclude such solvers from participating in competitions. This ensures no single solver can disrupt the system's operations.

This PR implements it by introducing a new struct, which checks whether the solver is allowed to participate in the next competition by using two different approaches:

1. Moved the existing `Authenticator`'s `is_solver` on-chain call into the new struct.
2. Introduced a new strategy, which finds a non-settling solver using a SQL query. It selects 3 last auctions(configurable) with a deadline until the current block to avoid selecting pending settlements and checks if all of the auctions were settled by the same solver/solvers(in case of multiple winners). This strategy caches the results to avoid redundant DB queries. This query relies on the auction_id column from the settlements table, which gets updated separately by the `Observer` struct, so the cache gets updated only once the `Observer` has some result.

These validators are called sequentially to avoid redundant RPC calls to `Authenticator`. So it first checks for the DB-based validator cache and, only then, sends the RPC call.

Once one of the strategies says the solver is not allowed to participate, it gets deny-listed for 5m(configurable).

Each validator can be enabled/disabled separately in case of any issue.

## Metrics

Added a metric that gets populated by the DB-based validator once a solver is marked as banned. The idea is to create an alert that is sent if there are more than 4 such occurrences for the last 30 minutes for the same solver, meaning it should be considered disabling the solver.

# Open discussions

1. Since the current SQL query filters out auctions where a deadline has not been reached, the following case is possible:
The solver gets banned, while the same solver has a pending settlement. In case this gets settled, the solver remains banned. While this is a niche case, it would be better to unblock the solver before the cache TTL deadline is reached. This has not been implemented in the current PR since some refactoring is required in the Observer struct. If this is approved, it can be implemented quickly.

2. Whether it makes sense to introduce a metrics-based strategy similar to the bad token detector's where the solver gets banned in case >95%(or similar) of settlements fail.

## How to test
A new SQL query test. Existing e2e tests.

## Related Issues

Fixes #3221 

## Summary by CodeRabbit

- New Features
 - Introduced advanced solver participation controls with configurable eligibility checks, integrating both on-chain and database validations.
 - Enabled asynchronous real-time notifications for settlement updates, enhancing system responsiveness.
 - Added metrics tracking to monitor auction participation and performance.

- Chores
 - Updated internal dependencies and restructured driver configuration.
 - Reorganized the database schema to support improved auction and settlement processing.

### CODE REVIEW

File: crates/autopilot/src/database/competition.rs [hunk 1]
```diff
@@ -139,4 +139,28 @@ impl super::Postgres {
 
         Ok(())
     }
+
+    /// Finds solvers that won `last_auctions_count` consecutive auctions but
+    /// never settled any of them. The current block is used to prevent
```
Comment (MartinquaXD) [inline crates/autopilot/src/database/competition.rs:144]: I'd say the problem is not exclusive to solvers that win repeatedly. It's worse for the protocol when a failing solver wins repeatedly but conceptually the check should protect any malfunctioning solver from participating in the auction. If it only wins 10% of the cases but fails to settle a majority of them we should also disable that one.

File: crates/autopilot/src/domain/competition/solver_participation_guard.rs
Comment (MartinquaXD) [inline crates/autopilot/src/domain/competition/solver_participation_guard.rs:1]: I didn't fully think through whether this architecture is a great design to begin with but if it is I think this should probably be a separate module.
You could put the trait and the `SolverParticipationGuard` into `mod.rs` and have separate files for the 2 underlying implementations. Also by addressing the components with their path name you could make the struct names shorter.
For example `DatabaseSolverParticipationValidator` could turn into `participation_guard::db::Validator`.

File: crates/autopilot/src/run_loop.rs [hunk 2]
```diff
@@ -726,23 +736,14 @@ impl RunLoop {
...
-            .call()
-            .await
-            .map_err(|err| {
-                tracing::warn!(
-                    driver = driver.name,
-                    ?driver.submission_address,
-                    ?err,
-                    "failed to check if solver is deny listed"
-                );
+        let can_participate = self.solver_participation_guard.can_participate(&driver.submission_address).await.map_err(|err| {
```
Comment (MartinquaXD) [inline crates/autopilot/src/run_loop.rs:739]: This participation guard needs to be opt-in until there was a CIP enforcing that for every solver.

File: crates/autopilot/src/run_loop.rs [hunk 3]
```diff
@@ -726,23 +736,14 @@ impl RunLoop {
...
+            tracing::error!(?err, driver = %driver.name, ?driver.submission_address, "solver participation check failed");
                 SolveError::SolverDenyListed
-            })?;
+            }
+        )?;
 
-        // Do not send the request to the driver if the solver is denied
-        if !is_allowed {
+        // Do not send the request to the driver if the solver is deny-listed
+        if !can_participate {
```
Comment (MartinquaXD) [inline crates/autopilot/src/run_loop.rs:746]: We should either notify the driver on every missed auction or when it gets disabled so that the external team can debug what's wrong immediately.

File: crates/autopilot/src/arguments.rs [hunk 4]
```diff
@@ -242,6 +242,51 @@ pub struct Arguments {
...
+    /// The time-to-live for the solver participation blacklist cache.
+    #[clap(long, env, default_value = "5m", value_parser = humantime::parse_duration)]
+    pub solver_blacklist_cache_ttl: Duration,
+
+    /// The number of last auctions to check solver participation eligibility.
+    #[clap(long, env, default_value = "3")]
+    pub solver_last_auctions_participation_count: u32,
+}
+
+#[derive(Debug, Clone, clap::Parser)]
```
Comment (MartinquaXD) [inline crates/autopilot/src/arguments.rs:280]: I don't think we need to have this configurable. If the solver is deny listed on a smart contract level there is absolutely no way it could ever submit a solution. Not even if the driver is malicious. Also since this was enabled for a long time already and didn't cause issues I think we shouldn't introduce new flags now. IMO we already have too many configuration parameters and should make sure new ones are actually pulling their weight before adding them.

File: crates/autopilot/src/database/competition.rs (hunk 1 above)
Comment (squadgazzz) [reply crates/autopilot/src/database/competition.rs:144]: > If it only wins 10% of the cases but fails to settle a majority of them we should also disable that one.

Ok, that solves one of the discussion points from the PR description. I'd introduce it in a separate PR then since the current one is already too big.

Comment (squadgazzz) [reply crates/autopilot/src/database/competition.rs:144]: So, I think the metrics-based approach needs to be implemented in addition to the current SQL query, where the query quickly prevents protocol from being stuck(the original issue states only this problem), while the metrics-based is more about long-term estimation. Does it make sense?

File: crates/autopilot/src/run_loop.rs (hunk 2 above)
Comment (squadgazzz) [reply crates/autopilot/src/run_loop.rs:739]: Ok, this can be achieved by disabling the db-based validator in the config and using this option by default.

Comment (MartinquaXD) [reply crates/autopilot/src/run_loop.rs:739]: I meant it should be opt-in on a solver by solver basis.

File: crates/autopilot/src/database/competition.rs (hunk 1 above)
Comment (MartinquaXD) [reply crates/autopilot/src/database/competition.rs:144]: > I think the metrics-based approach needs to be implemented in addition to the current SQL query

I think detecting that `X%` of won and promised solutions of solver `S` didn't get onchain over the last `M` minutes should be doable using the DB, no?
> I'd introduce it in a separate PR then since the current one is already too big.

Makes sense

Comment (squadgazzz) [reply crates/autopilot/src/database/competition.rs:144]: > last `M` minutes

If only last `M` **auctions**, not minutes. Will test the query since it seems like it would require a much higher auctions range to fetch to build reasonable statistics.

File: crates/autopilot/src/run_loop.rs (hunk 3 above)
Comment (squadgazzz) [reply crates/autopilot/src/run_loop.rs:746]: Added a new config.

File: crates/autopilot/src/arguments.rs (hunk 4 above)
Comment (squadgazzz) [reply crates/autopilot/src/arguments.rs]: Removed.

File: crates/autopilot/src/run_loop.rs (hunk 2 above)
Comment (squadgazzz) [reply crates/autopilot/src/run_loop.rs:739]: Done.

File: crates/autopilot/src/run_loop.rs (hunk 3 above)
Comment (squadgazzz) [reply crates/autopilot/src/run_loop.rs:746]: Implementing the `/notify` endpoint is external's team responsibly, right? So we would just send a request without expecting all the external solvers implemented it.

Comment (squadgazzz) [reply crates/autopilot/src/run_loop.rs:746]: An attempt to implement it in a separate PR https://github.com/cowprotocol/services/pull/3262

**Review by mstrug — APPROVED** [review]
I like the approach which uses trait based validators list, as it is easily extensible.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+
+                        tracing::debug!(solvers = ?non_settling_solver_names, "found non-settling solvers");
+
+                        let now = Instant::now();
+                        non_settling_drivers
+                            .into_iter()
+                            // Check if solver accepted this feature. This should be removed once a CIP is
+                            // approved.
+                            .filter_map(|driver| {
+                                driver.accepts_unsettled_blocking.then_some(driver.submission_address)
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:96]: I believe this filtering can be avoided completely if you filter out drivers that disabled this feature right in the `Validator` constructor.

File: crates/autopilot/src/domain/settlement/observer.rs [hunk 6]
```diff
@@ -49,6 +60,12 @@ impl Observer {
                 }
             }
         }
+        if updated {
+            // Notify the solver participation guard that a settlement has been updated.
+            if let Err(err) = self.settlement_updates_sender.send(()) {
```
Comment (sunce86) [inline crates/autopilot/src/domain/settlement/observer.rs:65]: `settlement::Observer` mustn't be a trigger for `SolverParticipationGuard`'s maintenance loop. If at point X in time, one of the solvers starts winning and not settling for the next 10 auctions (which already happened in practice), this line won't be hit and the maintenance loop in the `SolverParticipationGuard` won't be executed, therefore won't serve it's purpose.

Instead, it should be triggered by something else. "On a new block" makes the most sense to me, since each new block potentially represents the deadline for one of the latest auctions. But, then, since auctions are supposed to be synced with blocks, why not just doing the whole validation in sync as already noted ☝️

**Review by sunce86 — CHANGES_REQUESTED** [review]
When I initially thought about this task, it was much simpler in my head.

Do we really need to do this in async way? Sure it is probably more efficient since we avoid spending time on the critical runloop path, but it does come with a cost of > 600 lines added, coupling this component with `settlement::Observer` and introducing caching as well.

Setting the review to "blocking" because of the mentioned issue with `settlement::Observer`. 👇 

Why not just:
1. Runloop starts
2. Validator calls one `infra` function that asks the db whether the solver is supposed to be banned (in 'just in time' manner) and the whole logic is implemented synchronously.

I also don't buy the redundant db calls argument since we call this functionality once per auction at most.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+                    Ok(non_settling_solvers) => {
+                        let non_settling_drivers = non_settling_solvers
+                            .into_iter()
+                            .filter_map(|solver| {
+                                let address = eth::Address(solver.0.into());
+                                if let Some(driver) = self_.0.drivers_by_address.get(&address) {
+                                    Metrics::get()
+                                        .non_settling_solver
+                                        .with_label_values(&[&driver.name]);
+                                    Some(driver.clone())
```
[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/domain/competition/participation_guard/db.rs:76]: Given that we are talking about collections with 1-3 elements size, this won't really improve anything. But I agree, 2 iterations seem redundant, so I simplified the code a bit.

**Comment by squadgazzz** [comment]
> Validator calls one infra function that asks the db whether the solver is supposed to be banned (in 'just in time' manner) and the whole logic is implemented synchronously.

@sunce86 , there is already another proposal for additional db-based statistics. These SQL queries are not so light we could afford to execute them right inside the run loop.

File: crates/autopilot/src/domain/settlement/observer.rs (hunk 6 above)
Comment (squadgazzz) [reply crates/autopilot/src/domain/settlement/observer.rs:65]: >  If at point X in time, one of the solvers starts winning and not settling for the next 10 auctions (which already happened in practice), this line won't be hit and the maintenance loop in the SolverParticipationGuard won't be executed, therefore won't serve it's purpose.

True, I think I missed that scenario. Thanks.

> "On a new block" 

That was the initial idea, but then I thought about other networks with higher block production rates, so I tried to avoid thas. Probably, using the `competition_auctions` table updates as a trigger would make sense.

**Comment by sunce86** [comment]
> > Validator calls one infra function that asks the db whether the solver is supposed to be banned (in 'just in time' manner) and the whole logic is implemented synchronously.
> 
> @sunce86 , there is already another proposal for additional db-based statistics. These SQL queries are not so light we could afford to execute them right inside the run loop.

Understood.

So, as you already mentioned ☝️ , `Validator` maintenance should probably be triggered by each new competition saved to database.
Can we then:
1. On each new competition saved, `infra::Persistence` triggers the `Validator` maintenance loop (it could even pass saved `Competition` object or just the data validator needs).
2. If not passed, `Validator` fetches the latest competition from infra (db) and puts it into it's cache
3. All types of validators analyze the same data cached in `Validator`.

Any issue with this approuch?

**Comment by squadgazzz** [comment]
> Any issue with this approuch?

If I got it correctly, you mean some kind of FIFO cache. There is still the settlements data that needs to be fetched from the DB. I thought about this initially, but it adds more complexity to the already non-trivial solution. With the current approach, all the data is received from one source.

**Comment by sunce86** [comment]
> There is still the settlements data that needs to be fetched from the DB.

Maybe Validator can be signalled from two sources:

1. Inform Validator when each competition/auction is saved.
2. Inform Validator when each settlement is observed onchain.

Then combine those data internally in Validator to match each settlement to each competition/auction and deduct which competitions ended up without settlement (using auction deadline block).

**Comment by squadgazzz** [comment]
> Then combine those data internally in Validator to match each settlement to each competition/auction and deduct which competitions ended up without settlement (using auction deadline block).

Why I initially didn't go with this approach(mostly because of the second point):
1. At first glance, it seems more complex than SQL queries. Retrieve two different types of data from different sources. Update the data accordingly. Maintain a reasonable cache size.
2. On each restart, for the statistic-based validators, it would require either executing an SQL query to populate the initial data or waiting for N auctions to accumulate enough data to start blocking the solvers.

@sunce86 Does it make sense? I am not against implementing a more complex and probably more efficient approach, but the only benefit I see is the reduction of DB queries.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs (hunk 5 above)
Comment (squadgazzz) [reply crates/autopilot/src/domain/competition/participation_guard/db.rs:96]: The on-call week erased some contexts from my head. Initially, I filtered out drivers in the constructor, but then I had to implement this approach. Trying to remember what was the reason 🙈

Comment (squadgazzz) [reply crates/autopilot/src/domain/competition/participation_guard/db.rs:96]: This log and the metric were the reason: https://github.com/cowprotocol/services/blob/a2710c695f7c42644fdbe94a1d2d4fd3ac420458/crates/autopilot/src/domain/competition/participation_guard/db.rs#L88
https://github.com/cowprotocol/services/blob/a2710c695f7c42644fdbe94a1d2d4fd3ac420458/crates/autopilot/src/domain/competition/participation_guard/db.rs#L73-L75
Without the full drivers set, there will be just addresses. Since this feature is expected to be enabled selectively, not for all the solvers, using this metric and the log we can identify the problematic solvers that didn't accept the feature but still show low performance.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+    },
+};
+
+/// Checks the DB by searching for solvers that won N last consecutive auctions
+/// but never settled any of them.
+#[derive(Clone)]
+pub(super) struct Validator(Arc<Inner>);
+
+struct Inner {
+    db: Postgres,
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:21]: nit: can we substitute this with

`persistence: infra::Persistence`

and move related db function to this infra module? This is how we decided to do things for all components inside `autopilot::domain`

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+    ttl: Duration,
+    last_auctions_count: u32,
+    drivers_by_address: HashMap<eth::Address, Arc<infra::Driver>>,
+}
+
+impl Validator {
+    pub fn new(
+        db: Postgres,
+        current_block: CurrentBlockWatcher,
+        settlement_updates_receiver: tokio::sync::mpsc::UnboundedReceiver<()>,
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:32]: rename to competition

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 10]
```diff
@@ -0,0 +1,123 @@
...
+    /// Update the internal cache only once the settlement table is updated to
+    /// avoid redundant DB queries.
+    fn start_maintenance(
+        &self,
+        mut settlement_updates_receiver: tokio::sync::mpsc::UnboundedReceiver<()>,
+        current_block: CurrentBlockWatcher,
+    ) {
+        let self_ = self.clone();
+        tokio::spawn(async move {
+            while settlement_updates_receiver.recv().await.is_some() {
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:59]: same rename to "competition"

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+                    .0
+                    .db
+                    .find_non_settling_solvers(self_.0.last_auctions_count, current_block)
+                    .await
+                {
+                    Ok(non_settling_solvers) => {
+                        let non_settling_drivers = non_settling_solvers
+                            .into_iter()
+                            .filter_map(|solver| {
+                                let address = eth::Address(solver.0.into());
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:71]: If you move `find_non_settling_solvers` to `infra::Persistence` this line won't be needed.

File: crates/autopilot/src/domain/competition/participation_guard/mod.rs [hunk 12]
```diff
@@ -0,0 +1,72 @@
...
+
+struct Inner {
+    /// Stores the validators in order they will be called.
+    validators: Vec<Box<dyn Validator + Send + Sync>>,
+}
+
+impl SolverParticipationGuard {
+    pub fn new(
+        eth: Ethereum,
+        db: Postgres,
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/mod.rs:27]: same, we should use `infra::Persistence` (I know, it's a bit annoying)

**Review by sunce86 — COMMENTED** [review]
Mostly nits.

Do you have in plan writing an e2e test for this? Otherwise I'm afraid we won't have a high conviction it's working properly and we would hope for the best in prod 🙏

**Comment by squadgazzz** [comment]
> Do you have in plan writing an e2e test for this?

Yep, I will open another PR since 600+ lines of the code are already too much.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+            drivers_by_address,
+        }));
+
+        self_.start_maintenance(competition_updates_receiver, current_block);
+
+        self_
+    }
+
+    /// Update the internal cache only once the settlement table is updated to
+    /// avoid redundant DB queries.
```
Comment (sunce86) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:50]: update comment

**Review by sunce86 — APPROVED** [review]
LG.

This new logic will always return at least one non-settling solver right? The one that is currently being settled. Not sure what to do with this information but you might want to skip logging/alerting for that special one.

**Comment by squadgazzz** [comment]
> This new logic will always return at least one non-settling solver right? The one that is currently being settled.

I didn't get why is that. The currently settling auction gets filtered out in the query because of this: https://github.com/cowprotocol/services/pull/3257/files#diff-ecc7354b24bcc39d93bfb90181abe577203cc25d8f94c9886b2f5f3f1b7894d5R112

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+
+#[async_trait::async_trait]
+impl super::Validator for Validator {
+    async fn is_allowed(&self, solver: &eth::Address) -> anyhow::Result<bool> {
+        if let Some(entry) = self.0.banned_solvers.get(solver) {
+            if Instant::now().duration_since(*entry.value()) < self.0.ttl {
+                return Ok(false);
+            } else {
+                self.0.banned_solvers.remove(solver);
+            }
```
Comment (MartinquaXD) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:117]: I think this could lead to deadlocks. .get() keeps a read lock into the map while .remove() would require a write lock.
Given that the number of solvers that will ever enter the map is very small I think we might as well not remove the banned solver at all.
```suggestion
            return Ok(entry.elapsed() >= self.0.ttl);
```

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 15]
```diff
@@ -0,0 +1,122 @@
...
+    /// updated to avoid redundant DB queries on each block or any other
+    /// timeout.
+    fn start_maintenance(
+        &self,
+        mut competition_updates_receiver: tokio::sync::mpsc::UnboundedReceiver<()>,
+        current_block: CurrentBlockWatcher,
+    ) {
+        let self_ = self.clone();
+        tokio::spawn(async move {
+            while competition_updates_receiver.recv().await.is_some() {
```
Comment (MartinquaXD) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:59]: This should always be `Some`, right? In that case I would put a `tracing::error!()` after the loop alerting that the loop exited.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 16]
```diff
@@ -0,0 +1,122 @@
...
+                            .for_each(|solver| {
+                                self_.0.banned_solvers.insert(solver, now);
+                            });
+                    }
+                    Err(err) => {
+                        tracing::warn!(?err, "error while searching for non-settling solvers")
+                    }
+                }
+            }
+        });
```
Comment (MartinquaXD) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:105]: Seems like this could be simplified a bit.
```suggestion
        tokio::spawn(async move {
            while competition_updates_receiver.recv().await.is_some() {
                let current_block = current_block.borrow().number;
                let non_settling_solvers = match self_
                    .0
                    .persistence
                    .find_non_settling_solvers(self_.0.last_auctions_count, current_block)
                    .await
                {
                    Ok(non_settling_solvers) => non_settling_solvers,
                    Err(err) => {
                        tracing::warn!(?err, "error while searching for non-settling solvers");
                        continue;
                    }
                };

                tracing::debug!(solvers = ?non_settling_solvers, "found non-settling solver");

                let now = Instant::now();
                for solver in non_settling_solvers {
                    let Some(driver) = self_.0.drivers_by_address.get(&solver) else {
                        continue;
                    };

                    Metrics::get()
                        .non_settling_solver
                        .with_label_values(&[&driver.name]);

                    // Check if solver accepted this feature. This should be removed once a CIP is
                    // approved.
                    if driver.accepts_unsettled_blocking {
                        tracing::debug!(?solver, "disabling solver temporarily");
                        self_.0.banned_solvers.insert(solver, now);
                    }
                }
            }
            tracing::error!("stream of settlement updates terminated unexpectedly");
        });
```

File: crates/autopilot/src/arguments.rs [hunk 17]
```diff
@@ -245,6 +245,30 @@ pub struct Arguments {
...
+        id = "db_enabled",
+        long = "db-based-solver-participation-guard-enabled",
+        env = "DB_BASED_SOLVER_PARTICIPATION_GUARD_ENABLED",
+        default_value = "true"
+    )]
+    pub enabled: bool,
+
+    /// The time-to-live for the solver participation blacklist cache.
+    #[clap(long, env, default_value = "5m", value_parser = humantime::parse_duration)]
+    pub solver_blacklist_cache_ttl: Duration,
```
Comment (MartinquaXD) [inline crates/autopilot/src/arguments.rs:267]: This effectively determines how long a solver should be timed out, right? In that case this comment could be more self explanatory IMO.

File: crates/autopilot/src/infra/solvers/mod.rs [hunk 18]
```diff
@@ -21,6 +21,7 @@ pub struct Driver {
     // another driver solved with surplus exceeding this driver's surplus by `threshold`
     pub fairness_threshold: Option<eth::Ether>,
     pub submission_address: eth::Address,
+    pub accepts_unsettled_blocking: bool,
```
Comment (MartinquaXD) [inline crates/autopilot/src/infra/solvers/mod.rs:24]: Not sure the name is great. Perhaps `requested_timeout_on_problems` instead?

File: crates/autopilot/src/run.rs [hunk 19]
```diff
@@ -557,27 +561,41 @@ pub async fn run(args: Arguments) {
...
 
+    let solver_participation_guard = SolverParticipationGuard::new(
+        eth.clone(),
+        persistence.clone(),
+        competition_updates_receiver,
+        args.db_based_solver_participation_guard,
+        drivers
+            .iter()
+            .map(|driver| (driver.submission_address, driver.clone()))
+            .collect(),
```
Comment (MartinquaXD) [inline crates/autopilot/src/run.rs:585]: nit: storing the drivers in a map is an implementation detail the `Guard` cares about. Therefore it makes more sense to me for it to take an `impl IntoIterator<Item = Arc<Driver>>` and build the hashmap in the constructor. This would also avoid the possibility that the code to build the map has to be implemented multiple times.

File: crates/database/src/solver_competition.rs [hunk 20]
```diff
@@ -97,6 +97,57 @@ GROUP BY sc.id
     sqlx::query_as(QUERY).bind(tx_hash).fetch_optional(ex).await
 }
 
+pub async fn find_non_settling_solvers(
```
Comment (MartinquaXD) [inline crates/database/src/solver_competition.rs:100]: This query is quite big an gets executed during every auction if I'm not mistaken. Did you benchmark how well it performs?
Also a comment explaining what this query is supposed to do would be good.

File: crates/autopilot/src/run_loop.rs [hunk 21]
```diff
@@ -725,23 +747,14 @@ impl RunLoop {
...
-            .call()
-            .await
-            .map_err(|err| {
-                tracing::warn!(
-                    driver = driver.name,
-                    ?driver.submission_address,
-                    ?err,
-                    "failed to check if solver is deny listed"
-                );
+        let can_participate = self.solver_participation_guard.can_participate(&driver.submission_address).await.map_err(|err| {
```
Comment (MartinquaXD) [inline crates/autopilot/src/run_loop.rs:750]: Given that we fight for every little bit of time it would probably be better to already send the request to the solver and in the meantime run the query. If it turns out the solver should be deny-listed we just discard the solution.
Given that this should be the exception not the regular case this seems like the better approach to me.
Also this drastically reduces the performance requirements for the query. If we run it before sending a request to the solver it should probably finish in a few ms but if we run it while the solver is already computing a solution it wouldn't be a problem if it takes a second or 2.

**Review by MartinquaXD — COMMENTED** [review]
Running a DB query on every auction makes the code easier but I'm a bit worried about the performance. Do we already have the right queries to make this fast?

File: crates/autopilot/src/arguments.rs [hunk 22]
```diff
@@ -432,18 +463,34 @@ impl FromStr for Solver {
...
+
+        if let Some(value) = parts.get(3) {
+            match U256::from_dec_str(value) {
+                Ok(parsed_fairness_threshold) => {
+                    fairness_threshold = Some(parsed_fairness_threshold);
+                }
+                Err(_) => {
+                    accepts_unsettled_blocking = value
+                        .parse()
+                        .context("failed to parse solver's third arg param")?
```
[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/arguments.rs:477]: I hope this will be a temporary value until CIP is approved.

File: crates/autopilot/src/arguments.rs [hunk 23]
```diff
@@ -432,18 +463,34 @@ impl FromStr for Solver {
...
+                }
             }
-            None => None,
         };
 
+        if let Some(value) = parts.get(4) {
+            accepts_unsettled_blocking = value
```
Comment (m-lord-renkse) [inline crates/autopilot/src/arguments.rs:483]: This being a bool is really confusing, when you see the config you see `solver_name|address|true`, `true` is very generic, please consider some meaningful string.

File: crates/autopilot/src/arguments.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (m-lord-renkse) [reply crates/autopilot/src/arguments.rs:477]: I agree with @MartinquaXD , hopefully we will do that soon 🙏

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 24]
```diff
@@ -0,0 +1,122 @@
...
+        persistence: infra::Persistence,
+        current_block: CurrentBlockWatcher,
+        competition_updates_receiver: tokio::sync::mpsc::UnboundedReceiver<()>,
+        ttl: Duration,
+        last_auctions_count: u32,
+        drivers_by_address: HashMap<eth::Address, Arc<infra::Driver>>,
+    ) -> Self {
+        let self_ = Self(Arc::new(Inner {
+            persistence,
+            banned_solvers: Default::default(),
```
Comment (m-lord-renkse) [inline crates/autopilot/src/domain/competition/participation_guard/db.rs:38]: banned solvers will be unbannded for each service restart. Is that what we want?

File: crates/autopilot/src/run_loop.rs (hunk 21 above)
Comment (squadgazzz) [reply crates/autopilot/src/run_loop.rs:750]: > Also this drastically reduces the performance requirements for the query.

All the DB queries get executed in a background task outside the runloop.

File: crates/database/src/solver_competition.rs (hunk 20 above)
Comment (squadgazzz) [reply crates/database/src/solver_competition.rs:112]: It gets executed in a background task outside the runloop. The execution is triggered based on the updates of the `proposed_solutions` and `proposed_trade_executions` tables.

Comment (squadgazzz) [reply crates/database/src/solver_competition.rs:112]: The execution of the query is tested and it completes within 2s since the auction amount is limited by a small number.

File: crates/autopilot/src/infra/solvers/mod.rs (hunk 18 above)
Comment (squadgazzz) [reply crates/autopilot/src/infra/solvers/mod.rs:24]: What type should `requested_timeout_on_problems` contain then? Duration for how long can the solver be banned?

File: crates/autopilot/src/domain/competition/participation_guard/db.rs (hunk 16 above)
Comment (squadgazzz) [reply crates/autopilot/src/domain/competition/participation_guard/db.rs]: The updated approach uses solver addresses instead of their names. Not sure this will be useful in the logs.

File: crates/autopilot/src/domain/competition/participation_guard/db.rs [hunk 25]
```diff
@@ -0,0 +1,108 @@
...
+                    Ok(non_settling_solvers) => non_settling_solvers,
+                    Err(err) => {
+                        tracing::warn!(?err, "error while searching for non-settling solvers");
+                        continue;
+                    }
+                };
+
+                let mut non_settling_solver_names: Vec<&str> = Vec::new();
+                let now = Instant::now();
+                for solver in non_settling_solvers {
```
[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/domain/competition/participation_guard/db.rs:76]: >  + for_each()

This vec is required to then print all the found names in a single log:
```
tracing::debug!(solvers = ?non_settling_solver_names, "found non-settling solvers");
```

[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/domain/competition/participation_guard/db.rs]: Slightly updated the code to remove the mutable vec.

**Review by m-lord-renkse — APPROVED** [review]
Nice!

**Review by MartinquaXD — APPROVED** [review]
Change looks okay to me. But let's hold off with merging until the e2e test has been reviewed/approved as well.
