### PR TITLE
Do not preprocess COW AMMs when not configured

### LINKED ISSUE #3890: bug:Irrelevant warning messages.
### Problem
There are now a bunch of warnings.

```
driver::domain::cow_amm: no helper contract configured for CoW AMM factory
```

even if I don't have any cow-amms section in my config (I don't want the driver to fetch cow amms).

### Impact
Not critical, just pollutes the logs (they are warnings).

### To reproduce
Run the driver without any contracts.cow-amms section.

### Expected behaviour
No cow amm related logs when we dont care about cowamms.

### services version/commit hash and environment
v2.234.1

### PR DESCRIPTION
**Pull request by squadgazzz**
# Description
When the driver's COW AMM config is empty, the corresponding task still tries to search for surplus capturing jit order owners among the AMMs and fires a redundant warning log in that case. When the driver doesn't expect any AMMs, this log doesn't make any sense. This PR fixes this.

# Changes

- [ ] Make the COW AMM cache optional based on the COW AMMs config.
- [ ] When None, return fast with no AMMs for every auction with no redundant logs.

## How to test
Logs on chains where COW AMMs are not configured.

## Related Issues

Fixes #3890

### CODE REVIEW

File: crates/driver/src/domain/competition/pre_processing.rs [hunk 1]
```diff
@@ -394,8 +394,12 @@ impl Utilities {
         let _timer2 =
             observe::metrics::metrics().on_auction_overhead_start("driver", "cow_amm_orders");
 
-        let cow_amms = self
-            .cow_amm_cache
+        let Some(ref cow_amm_cache) = self.cow_amm_cache else {
+            // CoW AMM is not configured, return empty vec
+            return Arc::new(Default::default());
```
Comment (jmg-duarte) [inline crates/driver/src/domain/competition/pre_processing.rs]: Nit: Arc<T> impls Default where T impls Defaults
```suggestion
            return Default::default();
```

**Review by jmg-duarte — APPROVED** [review]
