### PR TITLE
Init liquidity in background

### LINKED ISSUE #1525: Better handling of start up crashes due to external services being unavailable
Sometimes when we restart pods they panic on start up for while due an external service not being available. The ones I'm aware of happening recently are due to using the graph:

- failed to create Balancer pool fetcher: failed to execute query on subgraph, /src/crates/solver/src/run.rs:218:14
- innitializing Uniswap V3 pool fetcher: error decoding response body: expected value at line 1 column 1, /src/crates/orderbook/src/run.rs:296:14

Panicking isn't great because it is creates spammy logs and it just doesn't feel like the right response to an external service that could also stop working any time later after initial startup, which wouldn't cause a panic. I have the following ideas for how to improve this:

- On startup, don't unwrap but wait for the initialization to succeed, retrying it. Maybe with some time limit at which it panics anyway.
- Succeed start up but keep the component that needs initialization disabled. Meaning we wouldn't get balancer and univ3 pools until it gets initialized.

In either case we can have a metric that tracks initialization status too so that we can alert on it.

Edit: On the other hand, if the subgraph is only used during start up then the argument that the service could go away later doesn't hold. And it might be confusing to have some kind of liquidity enabled but it silently not working because the subgraph is down.

### PR DESCRIPTION
**Pull request by MartinquaXD**
Fixes #1525

When we restart the services we need to initialize `BalancerV2` and `UniswapV3` liquidity. That uses the graph and this is very unreliable. So far the process has been:
1. restart service and 🙏 that the graph works
2. see that it doesn't and disable `UniswapV3` and `BalancerV2`
3. periodically check if the graph works again to re-enable the liquidity

With this change we move liquidity initialization into a background task that retries until it succeeds.

### Test Plan
Unit test to verify logic
Manual test to verify logs

### CODE REVIEW

File: crates/driver/src/infra/liquidity/config.rs [hunk 1]
```diff
@@ -124,7 +124,7 @@ impl UniswapV3 {
     pub fn uniswap_v3(network: &eth::NetworkId) -> Option<Self> {
         Some(Self {
             router: deployment_address(contracts::UniswapV3SwapRouter::raw_contract(), network)?,
-            max_pools_to_initialize: 50,
+            max_pools_to_initialize: 100,
```
Comment (nlordell) [inline crates/driver/src/infra/liquidity/config.rs:127]: Is there a reason we want to increase this again?

Comment (MartinquaXD) [reply crates/driver/src/infra/liquidity/config.rs:127]: This is the default in the current infra so I wanted to make it consistent.

File: crates/solver/src/liquidity_collector.rs [hunk 2]
```diff
@@ -43,3 +45,136 @@ impl LiquidityCollecting for LiquidityCollector {
...
+        let liquidity_source: Arc<Mutex<Option<L>>> = Default::default();
+        let inner = liquidity_source.clone();
+        tokio::task::spawn(
+            async move {
+                loop {
+                    match init().await {
+                        Err(err) => {
+                            tracing::warn!(
+                                "failed to initialise liquidity source; next init attempt in \
+                                 {retry_init_timeout:?}: {err:?}"
```
Comment (nlordell) [inline crates/solver/src/liquidity_collector.rs:75]: nit: `Duration: Debug` is kind of ugly - I would do something like:
```suggestion
                                 {}s: {err:?}", retry_init_timeout.as_secs_f64()
```

File: crates/solver/src/liquidity_collector.rs [hunk 3]
```diff
@@ -43,3 +45,136 @@ impl LiquidityCollecting for LiquidityCollector {
...
+    pub fn new<I, F>(label: &str, init: I, retry_init_timeout: Duration) -> Self
+    where
+        I: Fn() -> F + Send + Sync + 'static,
+        F: Future<Output = Result<L>> + Send,
+        L: LiquidityCollecting + 'static,
+    {
+        let liquidity_source: Arc<Mutex<Option<L>>> = Default::default();
+        let inner = liquidity_source.clone();
+        tokio::task::spawn(
+            async move {
```
Comment (nlordell) [inline crates/solver/src/liquidity_collector.rs:69]: I wonder if we should setup a metric for alerts here - otherwise, we may be silently running without UniV3 or BalV2 liquidity without anyone knowing.

It sounds like an "unactionable" alert, but my argument is that "notifying the team in the `#general` channel" should be the corresponding action. Not sure how this fits into the new on-call plan, (maybe @fleupold can share his view on this as well).

**Review by nlordell — APPROVED** [review]
Yay! LGTM, just one open question about observability (but not blocking the PR in general).

File: crates/solver/src/liquidity_collector.rs (hunk 2 above)
Comment (MartinquaXD) [reply crates/solver/src/liquidity_collector.rs:75]: That will literally print the same thing. 😅

Comment (nlordell) [reply crates/solver/src/liquidity_collector.rs:75]: What? I thought `Duration: Debug` prints something like `Duration { secs: 0, nanosecs: 1000 }` - or am I thinking of a different thing?

Comment (MartinquaXD) [reply crates/solver/src/liquidity_collector.rs:75]: That's `Instant`

Comment (nlordell) [reply crates/solver/src/liquidity_collector.rs:75]: Nice! I'm in the [lucky 10000](https://xkcd.com/1053/) today!

File: crates/solver/src/liquidity_collector.rs (hunk 3 above)
Comment (MartinquaXD) [reply crates/solver/src/liquidity_collector.rs:69]: Not sure how much good it would do if #general knew about that. I think the only difference would be that colleagues **might** not raise any issues in #oncall because they knew that liquidity is bad at the moment.
However, since the retry logic basically fixes the liquidity as soon as possible people might not even notice.

In any case if we decide that we want to have metrics I would add them in a separate PR.

**Comment by sunce86** [comment]
Nice improvement.

Additionally, I was hoping we could cache the latest valid states to db, and fallback to those in case the graph is down for extended period of time on app startup. Mainly because of UniV3 which can initialise even with a few hours old state (it can catch up).
But I think we can also do this inside the UniV3PoolFetcher -> save the result of  `get_registered_pools()` to db and read if whenever the function fails next time, so it is complaint with this PR.

File: crates/solver/src/liquidity_collector.rs (hunk 3 above)
Comment (fleupold) [reply crates/solver/src/liquidity_collector.rs:69]: I think we should alert if we are running without Balancer and v3 liquidity for an extended period of time (e.g. 1h). This would be actionable or at least noteworthy to me as it significantly reduces the quality of service

**Comment by MartinquaXD** [comment]
> Additionally, I was hoping we could cache the latest valid states to db

This makes sense to me. One thing I slightly dislike about that is that it would add things to the DB which are basically just an optimisation and not strictly required for the protocol to work. Maybe something like that would fit nicely with `arak` which was intended to get rid of the graph in the first place AFAIK.
Since the change of this PR is just a wrapper around existing code it will be easy to get rid of once we have the more optimal solution (persisting the state to DB) in place.

File: crates/solver/src/liquidity_collector.rs (hunk 3 above)
Comment (MartinquaXD) [reply crates/solver/src/liquidity_collector.rs:69]: Alright, will follow up with a PR for metrics.
