### PR TITLE
Don't count surplus of liquidity JIT orders in autopilot

### LINKED ISSUE #2684: bug: Don't count surplus of liquidity JIT orders in autopilot
### Problem
Unless I'm misreading things the autopilot currently sums up surplus for all orders traded in an auction.

### Impact
 Since JIT orders can not be differentiated from regular cowswap orders they would currently count towards surplus in the autopilot which might skew further analytics or alerting based on that data.

### Expected behaviour
Only orders that are eligible to count towards surplus actually do that in the autopilot score computation for settlements found on-chain.
When adding this exception for liquidity JIT orders we might as well also add code to allow surplus from CoW AMM JIT orders.
Another thing that might be tackled in a separate PR is not counting surplus for any regular cowswap order that was not part of the associated auction. My understanding is that if an order was not part of an auction it should not count towards surplus.
This would mostly happen if the solver crawls the orderbook on its own to add any open orders that were not in the respective auction for some reason.

### PR DESCRIPTION
**Pull request by squadgazzz**
# Description
Exclude JIT order from counting surplus in autopilot by checking if the order's uid doesn't exist in DB, meaning it is a JIT order. To avoid decoding order_uids multiple times, I refactored the code a little bit to compute ids while the trade is decoded.

## How to test
Added a DB query test.

## Related Issues
Fixes #2684

### CODE REVIEW

File: crates/autopilot/src/decoded_settlement.rs [hunk 1]
```diff
@@ -97,6 +98,12 @@ impl DecodedTrade {
     }
 }
 
+#[derive(Debug, PartialEq, Eq)]
+pub struct TradeWithOrderUid {
+    pub inner: DecodedTrade,
+    pub order_uid: OrderUid,
+}
```
Comment (squadgazzz) [inline crates/autopilot/src/decoded_settlement.rs:105]: I tried to avoid this type by adding the order_uid right into the DecodedTrade, but that led to problems to maintain the proper logging here: https://github.com/cowprotocol/services/pull/2688/files#diff-a8d36d62f168f7d7edcae25a871749822c1d249f561b19e39fac4514f0622087R251-R256

Comment (MartinquaXD) [reply crates/autopilot/src/decoded_settlement.rs:105]: I think I would just make `uid` a field on `DecodedTrade` and default initialize it and then afterwards call `DecodedTrade::compute_uid()` (now renamed private function) and set the `uid` field to the computed value.
That way you can still log all the raw data when decoding fails but you don't have an awkward wrapper type.

File: crates/autopilot/src/decoded_settlement.rs [hunk 2]
```diff
@@ -231,76 +241,84 @@ impl DecodedSettlement {
...
     /// solution.
-    pub fn total_surplus(&self, external_prices: &ExternalPrices) -> U256 {
-        self.trades.iter().fold(0.into(), |acc, trade| {
-            acc + match surplus(trade, &self.tokens, &self.clearing_prices, external_prices) {
-                Some(surplus) => surplus,
-                None => {
+    pub fn total_surplus(
+        &self,
+        external_prices: &ExternalPrices,
+        jit_order_uids: HashSet<OrderUid>,
```
Comment (MartinquaXD) [inline crates/autopilot/src/decoded_settlement.rs:276]:
```suggestion
        jit_order_uids: &HashSet<OrderUid>,
```

File: crates/autopilot/src/on_settlement_event_updater.rs [hunk 3]
```diff
@@ -212,13 +218,14 @@ impl Inner {
         );
 
         // surplus and fees calculation
-        let surplus = settlement.total_surplus(&external_prices);
+        let jit_order_uids = Postgres::get_missing_order_uids(
```
Comment (fleupold) [inline crates/autopilot/src/on_settlement_event_updater.rs:221]: I don't think this is the right approach, since it could lead to race conditions where an order that was inserted after the auction had been cut and sent to solvers still gets count. Doesn't the autopilot have the auction it sent to the solvers for a specific auction ID (we can read it from disk or cache it in memory). This auction contains all order uids that should count towards surplus (regular orders + smart orders which are allowed to produce surplus capturing JIT orders). Anything that's not in this list should be exempt from surplus.

File: crates/autopilot/src/decoded_settlement.rs (hunk 2 above)
Comment (fleupold) [inline crates/autopilot/src/decoded_settlement.rs:276]: I think this should take the original auction instance which contains prices and all eligible order uids

File: crates/autopilot/src/on_settlement_event_updater.rs (hunk 3 above)
Comment (MartinquaXD) [reply crates/autopilot/src/on_settlement_event_updater.rs:221]: > since it could lead to race conditions where an order that was inserted after the auction had been cut and sent to solvers still gets count. Doesn't the autopilot have the auction it sent to the solvers for a specific auction ID (we can read it from disk or cache it in memory).

The concern about the race condition is true and there are even more false positives (e.g. solver can store and settle open orders which were not part of the auction due to missing native prices). However, AFAIK we don't have this information available so we settled on this intermediate solution which would already support CoW AMM orders while still being a strict improvement over the status quo even if it's not perfect, yet.
The goal was to unblock support for CoW AMM orders ASAP while allowing us to come up with a PR that implements the bullet proof solution with a DB migration.

Comment (fleupold) [reply crates/autopilot/src/on_settlement_event_updater.rs:221]: I am talking about storing the current auction that - just 10 seconds before - was sent to the solvers containing the problem they solved, somewhere potentially in memory (I am also pretty sure it's already stored in the db though. How else does the solution competition endpoint get the list of order uids it contained?)

Any issue with reindexing logic will likely not be fixed while the current auction is being solved (and even if we don't want it to apply to an auction that has already been sent to solvers).

With this approach we are adding more scattered DB reads (which are not using the same query logic as other places that try to reconstruct the auction) which I think creates more technical debt than is worth.

Comment (fleupold) [reply crates/autopilot/src/on_settlement_event_updater.rs:221]: I honestly think 3 is as good (if not less hacky) than this. If the format changes, we can also change the logic we use here (as this is only important for new auctions and never done on historic ones).

My main annoyance is that we are introducing yet another way of fetching data (which is doomed to be inconsistent). Refactoring this will be much harder to "prioritise" than adjusting the logic if we are changing the schema of the solver competition endpoint.

Comment (sunce86) [reply crates/autopilot/src/on_settlement_event_updater.rs:221]: I am ok with doing (3) or (4) as a temporary fix to unblock COWAMM but, after that, we should make a proper solution:
1. Save <auction, order_uid> into database (similar to how we store auction prices).
2. Implement logic of counting/not counting in the autopilot domain https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/domain/settlement/mod.rs. However, this is obviously still not ready to be used instead of "decoded_settlement.rs" (will work on it)

File: crates/autopilot/src/decoded_settlement.rs (hunk 1 above)
Comment (sunce86) [reply crates/autopilot/src/decoded_settlement.rs:105]: Too bad domain settlement code is not yet ready to be used. There, we already have order_uid: https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/domain/settlement/trade.rs#L15

File: crates/autopilot/src/on_settlement_event_updater.rs (hunk 3 above)
Comment (MartinquaXD) [reply crates/autopilot/src/on_settlement_event_updater.rs:221]: Then let's go for option 3 to unblock this pr and get cow amms on the road.

File: crates/autopilot/src/on_settlement_event_updater.rs [hunk 4]
```diff
@@ -218,13 +229,29 @@ impl Inner {
...
+            .map(|order| OrderUid(order.0))
+            .collect::<HashSet<_>>();
+        let surplus_exempt_order_uids = Postgres::get_missing_order_uids(
+            settlement.trades.iter().filter_map(|trade| {
+                // check persistence of the orders not in the competition
+                (!competition_order_uids.contains(&trade.order_uid)).then_some(trade.order_uid)
+            }),
+            ex,
+        )
+        .await?;
```
Comment (fleupold) [inline crates/autopilot/src/on_settlement_event_updater.rs:251]: Why do we still need to do this? We now have access to the auction, so anything that is in the settlement and not in the auction is exempt from surplus. We should not need this extra db roundtrip (this query is my main worry with the original PR)

File: crates/autopilot/src/decoded_settlement.rs [hunk 5]
```diff
@@ -226,69 +236,72 @@ impl DecodedSettlement {
...
-    }
-
-    /// Returns fees for all trades.
-    pub fn all_fees(
+    pub fn total_surplus(
         &self,
         external_prices: &ExternalPrices,
-        domain_separator: &DomainSeparator,
-    ) -> Vec<Fees> {
+        surplus_exempt_order_uids: &HashSet<OrderUid>,
```
Comment (fleupold) [inline crates/autopilot/src/decoded_settlement.rs:271]: I'm not sure this is the best way to handle this. You basically force the caller of total_surplus to think about and remember to fetch the original auction and excluded jit orders. What purpose do jit orders serve on this struct in the first place? Would it make sense to pass in the original auction into the constructor and do the separation there instead of carrying this around as an extra argument?

**Review by fleupold — CHANGES_REQUESTED** [review]
Let's please get rid of the `get_missing_order_uids` query. It adds complexity (yet another way to look at what is part of an auction and what isn't), should not be needed and can easily lead to inconsistencies.

File: crates/autopilot/src/on_settlement_event_updater.rs (hunk 4 above)
Comment (MartinquaXD) [reply crates/autopilot/src/on_settlement_event_updater.rs:251]: CoW AMM JIT orders will not be in the auction or DB but are still supposed to receive surplus.

File: crates/autopilot/src/decoded_settlement.rs (hunk 5 above)
Comment (MartinquaXD) [reply crates/autopilot/src/decoded_settlement.rs:271]: > What purpose do jit orders serve on this struct in the first place?

Not sure I understand the question. When computing the score we need to be aware about JIT orders in some way since CoW AMM JIT orders are supposed to receiver surplus.
The question is in what what way should the struct learn about which orders are allowed to receive surplus.

Comment (squadgazzz) [reply crates/autopilot/src/decoded_settlement.rs:271]: I don't think the auction can be a part of the `DecodedSettlement` struct since we first need to decode a settlement and extract an `auction_id` to fetch auction JSON from the `solver_competitions` table. Another option is introducing a new dto struct containing a decoded settlement with an auction.

File: crates/autopilot/src/decoded_settlement.rs (hunk 2 above)
Comment (sunce86) [reply crates/autopilot/src/decoded_settlement.rs]: I will take care of this in a new autopilot domain implementation.

File: crates/autopilot/src/decoded_settlement.rs (hunk 5 above)
Comment (sunce86) [reply crates/autopilot/src/decoded_settlement.rs]: Let's discuss this in a more detail here: https://github.com/cowprotocol/services/issues/2723

For now, I am fine implementing it here in a "just make it work" manner :), since this file will be dropped anyway quite soon.

Comment (fleupold) [reply crates/autopilot/src/decoded_settlement.rs]: > I don't think the auction can be a part of the DecodedSettlement struct since we first need to decode a settlement and extract an auction_id to fetch auction JSON from the solver_competitions table.

I think we could call a settlement as not decodable if we aren't able to create it **and** fetch the related auction.

File: crates/autopilot/src/decoded_settlement.rs [hunk 6]
```diff
@@ -226,69 +236,72 @@ impl DecodedSettlement {
...
-    }
-
-    /// Returns fees for all trades.
-    pub fn all_fees(
+    pub fn total_surplus(
         &self,
         external_prices: &ExternalPrices,
-        domain_separator: &DomainSeparator,
-    ) -> Vec<Fees> {
+        surplus_eligible_orders: &HashSet<OrderUid>,
```
Comment (fleupold) [inline crates/autopilot/src/decoded_settlement.rs:271]: This parameter probably deserves some explanation in the docs of this method. I think we should explain to a developer that stumbles across this code in 6 months why we need to have a concept of eligible orders...

nit:
```suggestion
        eligible_orders: &HashSet<OrderUid>,
```

File: crates/autopilot/src/on_settlement_event_updater.rs [hunk 7]
```diff
@@ -191,36 +196,33 @@ impl Inner {
...
-            .map(|(token, price)| (token.0, price.get().into()))
-            .collect::<BTreeMap<_, _>>();
+        let auction = Postgres::find_competition(auction_id, ex)
+            .await?
+            .context(format!(
+                "missing competition for auction_id={:?}",
+                auction_id
+            ))?
+            .common
+            .auction;
```
Comment (fleupold) [inline crates/autopilot/src/on_settlement_event_updater.rs:206]: Didn't we just create this new function in #2702? Is it really the intention to remove it again? Since this function is not used anywhere else, should we properly remove it?

**Review by fleupold — COMMENTED** [review]
Missing docs and clarification on whether it's intended to revert #2702 (in which case we should probably properly revert it)

File: crates/autopilot/src/on_settlement_event_updater.rs (hunk 7 above)
Comment (sunce86) [reply crates/autopilot/src/on_settlement_event_updater.rs:206]: Not sure I understand why is this needed? Is it because during autopilot competition we only store auction prices related to tokens contained in the user orders from winning solution? But we actually need prices for all tokens?
If that is true, than I would rather save all the prices to auction_prices (this is how it was implemented initially but I was playing smart and wanted to optimize for db space and save only what we need ) and keep the https://github.com/cowprotocol/services/pull/2702 function. We are not supposed to read from SolverCompetition table.

File: crates/autopilot/src/decoded_settlement.rs [hunk 8]
```diff
@@ -226,69 +236,74 @@ impl DecodedSettlement {
...
+                        Some(trade)
+                    }
+                    Err(err) => {
+                        tracing::error!(
+                            ?err,
+                            ?trade,
+                            "failed to calculate order uid, we don't know which order this trade \
+                             belongs to"
+                        );
+                        None
```
Comment (sunce86) [inline crates/autopilot/src/decoded_settlement.rs:252]: In general I don't think settlement should be considered valid if this error happens (it basically means we have a bug somewhere in our code). See new implementation that is supposed to replace this whole file: https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/domain/settlement/mod.rs#L122-L123

However fine leaving it as is, considering that
1. old code worked in the same way
2. don't expect this to ever be hit
3. new code will be used instead, quite soon

**Review by sunce86 — COMMENTED** [review]
~I think the PR makes the assumption that the JIT orders are not part of the DecodedSettlement::trades vector which is wrong.~

File: crates/autopilot/src/decoded_settlement.rs [hunk 9]
```diff
@@ -633,8 +648,13 @@ mod tests {
         let native_token = addr!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2");
         let external_prices =
             ExternalPrices::try_from_auction_prices(native_token, auction_external_prices).unwrap();
-        let surplus = settlement.total_surplus(&external_prices).to_f64_lossy(); // to_f64_lossy() to mimic what happens when value is saved for solver
-                                                                                 // competition
+        let surplus = settlement
+            .total_surplus(
+                &external_prices,
+                &settlement.trades.iter().map(|t| t.order_uid).collect(),
```
[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/decoded_settlement.rs:654]: Do we have JIT orders in this test case?

[the remark this answers is not in the document]
Comment (sunce86) [reply crates/autopilot/src/decoded_settlement.rs:654]: My bad, was looking at the test only to see intended way of populating the eligible orders list.

**Review by sunce86 — APPROVED** [review]
I think this PR is good enough to be merged to unblock COW Amm feature.

I am fine with creating a bit of technical debt in this case (like removing persistance from OnSettlementEventUpdater and using SolverCompetition table) but I expect those to be resolved as part of my refactoring of autopilot domain anyway.

Fine with removing persistence::get_auction_prices function since https://github.com/cowprotocol/services/pull/2734 adds a new persistence function that will fetch all auction and competition data altogether.

File: crates/autopilot/src/decoded_settlement.rs [hunk 10]
```diff
@@ -226,69 +236,74 @@ impl DecodedSettlement {
...
-                             belongs to"
-                        );
-                        return None;
-                    }
-                };
+            .filter(|trade| eligible_orders.contains(&trade.order_uid))
+            .fold(0.into(), |acc, trade| {
+                acc + surplus(trade, &self.tokens, &self.clearing_prices, external_prices)
+                    .unwrap_or_else(|| {
+                        tracing::warn!("possible incomplete surplus calculation");
```
Comment (MartinquaXD) [inline crates/autopilot/src/decoded_settlement.rs:281]: We should at least log the problematic trade here.

**Review by MartinquaXD — APPROVED** [review]
Looks correct to me.

File: crates/autopilot/src/decoded_settlement.rs [hunk 11]
```diff
@@ -209,12 +220,11 @@ impl DecodedSettlement {
...
-            tokens,
-            clearing_prices,
-            trades: trades
-                .into_iter()
-                .map(|trade| DecodedTrade {
+        let trades = trades
+            .into_iter()
+            .filter_map(|trade| {
+                let mut trade = DecodedTrade {
+                    order_uid: Default::default(),
```
Comment (fleupold) [inline crates/autopilot/src/decoded_settlement.rs:227]: This is weird. Is it valid to instantiate a DecodedTrade with such an invalid `order_uid` (in this case the field should be optional to indicate "this is not a real id")? If not, I think we should give it a constructor that can take the domain_seperator and tokens and returns an error if the uid cannot be recovered instead of allowing callsites to create invalid representations.

**Review by fleupold — APPROVED** [review]
One more comment about not allowing to instantiate decoded trades with a dummy uid, but nothing blocking.

File: crates/autopilot/src/decoded_settlement.rs (hunk 11 above)
Comment (squadgazzz) [reply crates/autopilot/src/decoded_settlement.rs:227]: I am always against such mutations, but this requires much more refactoring, and Dusan mentioned it will be changed in the upcoming PRs. I can make it optional and return an error in case the order is None when it is required.

Comment (fleupold) [reply crates/autopilot/src/decoded_settlement.rs:227]: Maybe I don't understand the issue. I'm in favor of keeping this field, just enforcing the struct gets instantiated via a constructor and if it fails we are not returning a broken object but an error. But sue, it doesn't make a huge difference so fee free to ignore if it causes issues.

Comment (squadgazzz) [reply crates/autopilot/src/decoded_settlement.rs]: A proposal: https://github.com/cowprotocol/services/pull/2688/commits/9cac26491f03d972d82ec00dd7c12f3edb6c0198

File: crates/autopilot/src/decoded_settlement.rs [hunk 12]
```diff
@@ -66,41 +68,83 @@ pub struct DecodedTrade {
...
+    receiver: Address,
+    sell_amount: U256,
+    buy_amount: U256,
+    valid_to: u32,
+    app_data: Bytes<[u8; 32]>,
+    fee_amount: U256,
+    flags: U256,
+    executed_amount: U256,
+    signature: Bytes<Vec<u8>>,
+}
```
[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/decoded_settlement.rs:86]: The intermediate type is useful for logging when the trade is not yet decoded, but we need something in the log already in case of an error. Printing a raw tuple would look useless there.

[the remark this answers is not in the document]
Comment (squadgazzz) [reply crates/autopilot/src/decoded_settlement.rs:86]: This log

https://github.com/cowprotocol/services/blob/jit-orders-surplus-exempt/crates/autopilot/src/decoded_settlement.rs#L271
