### PR TITLE
Revert #3546 (Revert #3489)

### LINKED ISSUE #3570: bug: investigate driver segfaults after autopilot change
### Problem
The introduction of https://github.com/cowprotocol/services/commit/8bf8e3b0be613ce3656ddc1f9dc3ea7dc430f407 led to segfaults

Starting with the merge at Aug 2nd, 8:38 — https://github.com/cowprotocol/services/commit/8bf8e3b0be613ce3656ddc1f9dc3ea7dc430f407
Which finished being built/deployed at Aug 2nd, 8:50 — https://github.com/cowprotocol/services/actions/runs/16691376291
After which segfaults started 2 minutes later.

There's a second PR that directly changes the driver (https://github.com/cowprotocol/services/pull/3450) which would make much more sense, but wasn't deployed at the time of the segfaults starting: https://github.com/cowprotocol/services/actions/runs/16691468799

### Impact
Not-critical as the PRs are no longer in main

### To reproduce
Couldn't reproduce

### Expected behaviour
No SEGFAULT

### Screenshots/logs
If applicable, add screenshots or logs to help explain your problem.

### services version/commit hash and environment
State the version of services where you've encountered the bug or, if built off a specific commit, the relevant commit hash.

Version / commit hash: 8bf8e3b0be613ce3656ddc1f9dc3ea7dc430f407
Environment: staging

### PR DESCRIPTION
**Pull request by jmg-duarte**
# Description
Revert #3546 (Revert #3489)

# Changes
Revert #3546 (Revert #3489)

## How to test
Was tested for ~24h in staging

## Related Issues

Fixes #3570

### CODE REVIEW

File: crates/e2e/tests/e2e/univ2.rs [hunk 1]
```diff
@@ -116,7 +116,7 @@ async fn test(web3: Web3) {
             // solver participated in the competition
             && data.participants.iter().any(|p| p.participant.0 == solver.address().0)
             // and won the auction
-            && data.reference_scores.first().is_some_and(|score| score.solver.0 == solver.address().0)
+                    && data.reference_scores[0].solver.0 == solver.address().0
```
Comment (MartinquaXD) [inline crates/e2e/tests/e2e/univ2.rs]: The original should be kept since that cannot panic. Also the new version has a wrong indentation.

**Review by MartinquaXD — APPROVED** [review]
LGTM, just 1 nit.
