### PR TITLE
Stricter 0x liquidity order filtering

### LINKED ISSUE #238: Stricter 0x liquidity order filtering
When we integrated 0x liquidity orders we saw a big increase in memory usage. This was mitigated by only keeping orders which trade our base tokens or tokens contained in user orders.

Unfortunately we learned that there is a huge variance in orders retained by that condition. For example this [thread](https://cowservices.slack.com/archives/C0361CDD1FZ/p1653923986832539) showed that many (>800) orders are trading the [HEX](https://etherscan.io/token/0x2b591e99afe9f32eaa6214f7b7629768c40eeb39) token. So if someone wants to trade this token our solver pods might encounter out-of-memory crashes.

Because it's not reasonable to assume that a single settlement would actually use that many orders it should be okay to reduce the set of collected orders further.
One approach could be to only keep a few of the biggest or best priced orders for each token pair.
This should give us a good selection for user orders.

### PR DESCRIPTION
**Pull request by ahhda**
Fixes #238 

This PR should resolve the memory issues that we face when we have too many orders by reducing the set of collected orders.

We do this by distributing our orders into buckets, where the key for each bucket is an ordered pair of tokens. We then reduce these buckets by taking only 5 best priced and 5 biggest volume orders from the list.

### Test Plan

* Apply this diff
    <details><summary>Fake Order diff</summary>
    
    ```
    diff --git a/crates/shared/src/zeroex_api.rs b/crates/shared/src/zeroex_api.rs
    index 8256ce9..aa4b8c9 100644
    --- a/crates/shared/src/zeroex_api.rs
    +++ b/crates/shared/src/zeroex_api.rs
    @@ -440,7 +440,7 @@ impl DefaultZeroExApi {
                 .text()
                 .await
                 .map_err(ZeroExResponseError::TextFetch)?;
    -        tracing::debug!("Response from 0x API: {}", response_text);
    +        // tracing::debug!("Response from 0x API: {}", response_text);
     
             match serde_json::from_str::<RawResponse<T>>(&response_text) {
                 Ok(RawResponse::ResponseOk(response)) => Ok(response),
    diff --git a/crates/solver/src/liquidity/zeroex.rs b/crates/solver/src/liquidity/zeroex.rs
    index 95db3a6..7644ea5 100644
    --- a/crates/solver/src/liquidity/zeroex.rs
    +++ b/crates/solver/src/liquidity/zeroex.rs
    @@ -4,6 +4,7 @@ use crate::liquidity::{Exchange, LimitOrder, Liquidity};
     use crate::settlement::SettlementEncoder;
     use anyhow::Result;
     use contracts::{GPv2Settlement, IZeroEx};
    +use hex_literal::hex;
     use model::order::OrderKind;
     use model::TokenPair;
     use primitive_types::{H160, U256};
    @@ -44,11 +45,17 @@ impl ZeroExLiquidity {
                         vec![]
                     }
                 });
    +        let fake_order = [TokenPair::new(
    +            H160(hex!("2b591e99afe9f32eaa6214f7b7629768c40eeb39")),
    +            H160::default(),
    +        )
    +        .unwrap()]
    +        .into_iter();
     
             let user_order_pairs = user_orders
                 .iter()
                 .filter_map(|order| TokenPair::new(order.buy_token, order.sell_token));
    -        let relevant_pairs = self.base_tokens.relevant_pairs(user_order_pairs);
    +        let relevant_pairs = self.base_tokens.relevant_pairs(fake_order);
     
             let order_buckets = self.generate_order_buckets(zeroex_orders, relevant_pairs);
             let filtered_zeroex_orders = self.get_useful_orders(order_buckets, 5);
    
    ```
    </details>

* Run docker container for postgres

    ```
    docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=`whoami` -p 5432:5432 docker.io/postgres
    docker run -ti -e FLYWAY_URL="jdbc:postgresql://host.docker.internal/?user="$USER"&password=" -v $PWD/database/sql:/flyway/sql cowprotocol/services-migration migrate
    ```

* Run orderbook
    ```
    export export NODE_URL="https://mainnet.infura.io/v3/KEY"
    cargo run --bin orderbook -- --skip-trace-api true --skip-event-sync
    ```
* Run solver
    ```
    export export NODE_URL="https://mainnet.infura.io/v3/KEY"
    cargo run -p solver -- \  
      --solver-account 0xa6DDBD0dE6B310819b49f680F65871beE85f517e \
      --transaction-strategy DryRun \
      --base-tokens "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0x6B175474E89094C44Da98b954EedeAC495271d0F,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,0xdAC17F958D2ee523a2206206994597C13D831ec7,0xc00e94Cb662C3520282E6f5717214004A7f26888,0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2,0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599,0x6810e776880C02933D47DB1b9fc05908e5386b96,0x2b591e99afe9f32eaa6214f7b7629768c40eeb39"
    ```

* If we print out the number of zeroex orders, we'll see that the number is now reduced significantly
    
    Screenshot 2022-06-03 at 1 14 36 PM

### Release notes

0x liquidity orders now keep only 5 of the biggest and 5 of the best-priced orders for each token pair.

### CODE REVIEW

File: crates/solver/src/liquidity/zeroex.rs [hunk 1]
```diff
@@ -47,20 +50,67 @@ impl ZeroExLiquidity {
...
+
+        Ok(filtered_zeroex_orders)
+    }
+
+    fn generate_order_buckets(
+        &self,
+        zeroex_orders: impl Iterator<Item = OrderRecord>,
+        relevant_pairs: HashSet<TokenPair>,
+    ) -> OrderBuckets {
+        // divide orders in buckets and choose best orders in those buckets
```
Comment (MartinquaXD) [inline crates/solver/src/liquidity/zeroex.rs:64]: nit: Choosing best orders happens in a different function.

File: crates/solver/src/liquidity/zeroex.rs [hunk 2]
```diff
@@ -47,20 +50,67 @@ impl ZeroExLiquidity {
...
+            orders.sort_by(|order_1, order_2| {
+                let price_1 = order_1.order.taker_amount as f64 / order_1.order.maker_amount as f64;
+                let price_2 = order_2.order.taker_amount as f64 / order_2.order.maker_amount as f64;
+                price_2.partial_cmp(&price_1).unwrap()
+            });
+            filtered_zeroex_orders.extend(orders.drain(orders.len() - orders_per_type..));
+
+            orders.sort_by_key(|order| order.metadata.remaining_fillable_taker_amount);
+            orders.reverse();
+            filtered_zeroex_orders.extend(orders.iter().take(orders_per_type).cloned());
```
Comment (MartinquaXD) [inline crates/solver/src/liquidity/zeroex.rs:104]: I remembered that instead of moving elements in the `Vec` around one can also just reverse the iterator (`iter().rev()`).
And instead of cloning the orders one can move them by using `into_iter()`.
Together that would look like this:
```rust
filtered_zeroex_orders.extend(orders.into_iter().rev().take(orders_per_type));
```

File: crates/solver/src/liquidity/zeroex.rs [hunk 3]
```diff
@@ -47,20 +50,67 @@ impl ZeroExLiquidity {
...
+        });
+        let filtered_zeroex_orders: Vec<_> = filtered_zeroex_orders
+            .into_iter()
+            .flat_map(|order| self.record_into_liquidity(order))
+            .collect();
+        filtered_zeroex_orders
     }
 
-    /// Turns 0x OrderRecord into liquidity which solvers can use.
+    // Turns 0x LimitOrder into liquidity which solvers can use.
```
Comment (MartinquaXD) [inline crates/solver/src/liquidity/zeroex.rs:113]: Since the function didn't need to be changed after all, leaving the comment as it was would reduce the size of the diff.

**Review by MartinquaXD — COMMENTED** [review]
I like the detailed manual test steps. Keep up your nice PR descriptions! 👍

Other than that the diff of the PR could be reduced slightly (some changes were not needed after all) and it would be nice to have some automated tests for the change as well.
Since the logic got split into 2 functions this should be doable.

File: crates/solver/src/liquidity/zeroex.rs (hunk 2 above)
Comment (MartinquaXD) [reply crates/solver/src/liquidity/zeroex.rs]: `orders.reverse()` is no longer necessary if you are iterating backwards over the `Vec` with `into_iter().rev()`.
Otherwise you would reverse twice effectively keeping the original order.

File: crates/solver/src/liquidity/zeroex.rs [hunk 4]
```diff
@@ -47,17 +50,64 @@ impl ZeroExLiquidity {
...
                     Some(pair) => relevant_pairs.contains(&pair),
                     None => false,
                 }
             })
-            .filter_map(|record| self.record_into_liquidity(record))
-            .collect();
+            .for_each(|order| {
+                let bucket = buckets
+                    .entry((order.order.maker_token, order.order.taker_token))
+                    .or_insert(vec![]);
```
Comment (vkgnosis) [inline crates/solver/src/liquidity/zeroex.rs:76]:
```suggestion
                    .or_default();
```

File: crates/solver/src/liquidity/zeroex.rs [hunk 5]
```diff
@@ -47,17 +50,64 @@ impl ZeroExLiquidity {
...
 
-        Ok(filtered_zeroex_orders)
+    /// Get the `orders_per_type` best priced and biggest volume orders.
+    fn get_useful_orders(
+        &self,
+        order_buckets: OrderBuckets,
+        orders_per_type: usize,
+    ) -> Vec<Liquidity> {
+        let mut filtered_zeroex_orders = vec![];
+        order_buckets.into_values().for_each(|mut orders| {
```
Comment (vkgnosis) [inline crates/solver/src/liquidity/zeroex.rs:89]: I slightly prefer a normal `for ...` loop rather than `for_each`. They are mostly equivalent (return becomes continue) but it feels more correct with a real for loop unless there is a good reason for the other way.

File: crates/solver/src/liquidity/zeroex.rs [hunk 6]
```diff
@@ -47,17 +50,64 @@ impl ZeroExLiquidity {
...
+                filtered_zeroex_orders.extend(orders);
+                return;
+            }
+            // Sorting to have best priced orders at the end of the vector
+            orders.sort_by(|order_1, order_2| {
+                let price_1 = order_1.order.taker_amount as f64 / order_1.order.maker_amount as f64;
+                let price_2 = order_2.order.taker_amount as f64 / order_2.order.maker_amount as f64;
+                price_2.partial_cmp(&price_1).unwrap()
+            });
+            filtered_zeroex_orders.extend(orders.drain(orders.len() - orders_per_type..));
```
Comment (vkgnosis) [inline crates/solver/src/liquidity/zeroex.rs:100]: This part is tricky because there are 3 things that decide the order:
1. which way to divide taker and maker amount
2. which way to partial_cmp (price 1 or price 2 first)
3. which way to take from the sorted vector (start or end)

The way I explained it in my head is that we want those orders that have the maximum maker_amount / taker_amount because we sell the taker amount and receive the maker amount. Based on that I think you can reverse the price calculation and return `price_1.partial_cmp(price_2)`. This feels more natural to me.

File: crates/solver/src/liquidity/zeroex.rs [hunk 7]
```diff
@@ -47,17 +50,64 @@ impl ZeroExLiquidity {
...
+
+            orders.sort_by_key(|order| order.metadata.remaining_fillable_taker_amount);
+            orders.reverse();
+            filtered_zeroex_orders.extend(orders.into_iter().rev().take(orders_per_type));
```
Comment (vkgnosis) [inline crates/solver/src/liquidity/zeroex.rs:104]: Like Martin said this is a double reverse. Should only need 1.

File: crates/solver/src/liquidity/zeroex.rs [hunk 8]
```diff
@@ -47,17 +50,64 @@ impl ZeroExLiquidity {
...
+        });
+        let filtered_zeroex_orders: Vec<_> = filtered_zeroex_orders
+            .into_iter()
+            .flat_map(|order| self.record_into_liquidity(order))
+            .collect();
+        filtered_zeroex_orders
```
Comment (vkgnosis) [inline crates/solver/src/liquidity/zeroex.rs:110]:
```suggestion
       filtered_zeroex_orders
            .into_iter()
            .flat_map(|order| self.record_into_liquidity(order))
            .collect()
```

**Review by vkgnosis — COMMENTED** [review]
This is a good change. I left some more nit picky comments about rust style. Would also like to see a unit test for the two cases (price and volume).

File: crates/solver/src/liquidity/zeroex.rs (hunk 6 above)
Comment (ahhda) [reply crates/solver/src/liquidity/zeroex.rs]: Changed the logic so that the comparison is between `maker_amount/taker_amount` ratio to have more clarity. Since this is sorted in ascending order and we are picking from the end (drain from the end in the next line), switched to `price_1.partial_cmp(price_2)`.

**Review by vkgnosis — APPROVED** [review]

File: crates/solver/src/liquidity/zeroex.rs [hunk 9]
```diff
@@ -107,3 +153,146 @@ impl SettlementHandling<LimitOrder> for OrderSettlementHandler {
...
+                taker_token: token_b,
+                maker_token: token_a,
+                ..order
+            },
+            metadata,
+        };
+        let order_buckets = ZeroExLiquidity::generate_order_buckets(
+            [bogous_order_1, bogous_order_2].into_iter(),
+            relevant_pairs,
+        );
```
Comment (MartinquaXD) [inline crates/solver/src/liquidity/zeroex.rs:190]: Would be nice to test what happens when you have orders which shouldn't end up in any bucket and a scenario where you have multiple orders ending up in the same bucket.

**Review by MartinquaXD — COMMENTED** [review]
Overall the test code looks reasonable so feel free to not use the refactoring suggestions but the 2 test cases I mentioned would be a good addition IMO.

File: crates/solver/src/liquidity/zeroex.rs [hunk 10]
```diff
@@ -107,3 +153,146 @@ impl SettlementHandling<LimitOrder> for OrderSettlementHandler {
...
+                ..Default::default()
+            },
+        };
+        let bogous_order_3 = OrderRecord {
+            order,
+            metadata: OrderMetadata {
+                remaining_fillable_taker_amount: 10000,
+                ..Default::default()
+            },
+        };
```
[the remark this answers is not in the document]
Comment (vkgnosis) [reply crates/solver/src/liquidity/zeroex.rs:231]: I like the helper closures too to reduce the amount of code.

File: crates/solver/src/liquidity/zeroex.rs [hunk 11]
```diff
@@ -107,3 +153,139 @@ impl SettlementHandling<LimitOrder> for OrderSettlementHandler {
...
+        let order_with_taker_amount = |taker_amount| OrderRecord {
+            order: Order {
+                taker_token: token_a,
+                maker_token: token_b,
+                taker_amount,
+                maker_amount: 100_000_000,
+                ..Default::default()
+            },
+            metadata: metadata.clone(),
+        };
```
Comment (MartinquaXD) [inline crates/solver/src/liquidity/zeroex.rs:278]: The `OrderRecord`s for this test are not quite right. The second step of `get_useful_orders()` sorts orders by `order.metadata.remaining_fillable_taker_amount`. Since `order_with_taker_amount()` doesn't set that field all orders are effectively identical in this regard (they all have 0 as the default).

**Review by MartinquaXD — APPROVED** [review]
Looks good to me. 🎉
