### PR TITLE
chore: fix flaky liquidity_source_notification test (#3748)

### LINKED ISSUE #3748: chore: Fix flaky test `forked_node_liquidity_source_notification_mainnet`
The `liquidity_source_notification::forked_node_liquidity_source_notification_mainnet` test has become flaky(or probably was flaky initially). This needs to be fixed.

### PR DESCRIPTION
**Pull request by mayanksharma-eth**
Fix flaky test in forked_node_liquidity_source_notification_mainnet

This PR addresses #3748 by making the Liquorice notification test wait until the mock server has actually recorded a request before asserting, which removes the race that caused the intermittent failure.

Local validation steps
Installed Anvil (Foundry) and spun up a fork at mainnet block 23326100.
Warmed the fork so the snapshot could be re-used offline (USDC/USDT contract reads, block fetch, etc.).
Re-ran the test against the local forked RPC (FORK_URL_MAINNET=http://127.0.0.1:8545), confirming it now passes consistently.
Removed the temporary notification-count logging after verifying the race was gone.
Closes #3748

### CODE REVIEW

File: crates/e2e/tests/e2e/liquidity_source_notification.rs [hunk 1]
```diff
@@ -332,6 +332,17 @@ http-timeout = "10s"
     assert!(trade.is_some());
 
     // Ensure that notification was delivered to Liquorice API
+    wait_for_condition(TIMEOUT, || async {
+        let state = liquorice_api.get_state().await;
+        tracing::info!(
+            "liquorice notification batch so far: {}",
+            state.notification_requests.len()
+        );
```
Comment (squadgazzz) [inline crates/e2e/tests/e2e/liquidity_source_notification.rs]: This log seems redundant.

**Comment by squadgazzz** [comment]
@codersharma2001 running locally doesn't mean anything, since we have issues in CI. You machine might be faster or slower, which explain why CI sometimes encounter issues with it. As I mentioned above, i tried to run you changes and the test fails again. Could you validate the branch I was running from and the failure reason? I might have missed something and it fails in different place?

**Comment by codersharma2001** [comment]
> @codersharma2001 running locally doesn't mean anything, since we have issues in CI. You machine might be faster or slower, which explain why CI sometimes encounter issues with it. As I mentioned above, i tried to run you changes and the test fails again. Could you validate the branch I was running from and the failure reason? I might have missed something and it fails in different place?

For quick reference:

Branch: [fix/flaky-liquidity-source-test](https://github.com/codersharma2001/services/tree/fix/flaky-liquidity-source-test)

Steps to run the forked Liquorice e2e (CI parity):

Start a fork source Anvil on 127.0.0.1:8546 (warm snapshot or direct fork, e.g. 

```anvil --fork-url https://eth-mainnet.g.alchemy.com/v2/xnNWnpBMlZABF_rBFjTf2aKBL-N3RkJN  \      --fork-block-number 23326100 \      --fork-retry-backoff 2000 \
      --retries 10 \
      --timeout 120000 \
      --preserve-historical-states \
      --port 8546 ). 
```

```export FORK_URL_MAINNET=http://127.0.0.1:8546.```


Run ```just test-e2e forked_node_liquidity_source_notification_mainnet``` (add NEXTEST_SUCCESS_OUTPUT=immediate if you want logs even on pass).

**Comment by codersharma2001** [comment]
> @codersharma2001, please accept the CLA, and we are ready for the merge.

I have accepted the CLA
